### ISSUE TITLE
[4.1] HttpClients rework

### ISSUE THREAD

**Issue by yguedidi** [facebook/facebook-php-sdk-v4#181]
For me, it doesn't make sense to technically be possible to call ``getResponseHeaders()`` or ``getResponseHttpStatusCode()`` before a call to ``send()``. (because they're public)
I propose to only have a ``send()`` method in ``FacebookHttpClientInterface`` that take headers in arguments (something like @SammyK did in #169) but instead returns the raw body, returns an array with the raw body, the status code and response header, because theses data are linked together.
_This will also ease tests of the coming ``FacebookClient``_ :)

@gfosco, @SammyK any thoughts ?

**Comment by SammyK** [comment]
Hey @yguedidi! All this stuff has been reworked so I think we can close this one too?

**Comment by yguedidi** [comment]
Yes!
