### ISSUE TITLE
[Proposal] Event Listener / Emitter

### ISSUE THREAD

**Issue by SammyK** [facebook/facebook-php-sdk-v4#217]
After debugging #216, it got me thinking we need to add some debugging log messages in the SDK. Perhaps using something like [`LoggerInterface`](https://github.com/php-fig/log).

I was thinking of how to implement this. We could just hard-code a bunch of log messages that do nothing if debug mode is off or echo or write to file if debug mode is on.

OR (and now we're finally getting to the proposal part lol) we could add a very basic event emitter to the SDK. So when an event happens (i.e. sending a request to graph), we'd fire a named event.

```php
$event->fire('sendRequest', $payload);
```

And you could add a listener to do something with the event:

```php
use Facebook\Events\Listener;
$eventListener = new Listener();

$eventListener->on('sendRequest', function ($payload) {
    // Log the event, or add something to a queue, or whatever
});

$eventListener->on('successResponse', function (FacebookResponse $response) {
    // Tell my framework about it
});
```

This would add quite a bit of functionality to the SDK, enabling developers to tie into many places of the SDK in a way they couldn't before.

What do you guys think?

**Comment by gfosco** [comment]
Closing this, feel free to reopen if there's new discussion later.

**Comment by SammyK** [comment]
I've got it on a personal TODO list so it will rear its head sometime in the near future. :D
