### ISSUE TITLE
[4.1] Add repo to TravisCI

### ISSUE THREAD

**Issue by SammyK** [facebook/facebook-php-sdk-v4#224]
Now that we have a `.travis.yml` file, we can add the repo to [TravisCI](https://travis-ci.org/) so all PR's can be auto-tested.

**Comment by yguedidi** [comment]
ping @gfosco

**Comment by gfosco** [comment]
![travis_ci_-_free_hosted_continuous_integration_platform_for_the_open_source_community](https://cloud.githubusercontent.com/assets/406732/6010927/95d502e8-aaeb-11e4-822d-5a71633a2784.png)

**Comment by SammyK** [comment]
Yay!
