### ISSUE TITLE
[4.1]getSessionFromRedirect in FacebookRedirectLoginHelper ?

### ISSUE THREAD

**Issue by serhatdurum** [facebook/facebook-php-sdk-v4#233]
Hi, 

I'm trying to new sdk.In the new "FacebookRedirectLoginHelper" has no function so i changed helper ->getAccessToken.Maybe we will update the docs or am i doing something wrong ? 

Btw, sendRequest func in "FacebookClient" doesn't throw any exception.

Thanks

**Comment by gfosco** [comment]
Closing this... let me know if we still have an issue here in 4.1..
