### ISSUE TITLE
getSessionFromRedirect() doesn't work from when redirected to mobile url

### ISSUE THREAD

**Issue by ayushchd** [facebook/facebook-php-sdk-v4#254]
When apps.facebook.com/xyz redirects to the mobile url (specified in the app settings) on a mobile device, it only sends ```code``` as the request parameter and not ```state``` as this request does not originate from within the app. As a result, when trying retrieve the session, using ```FacebookRedirectLoginHelper::getSessionFromRedirect()``` returns ```null``` as the method validates the ```state``` parameter to provide against CSRF attacks which is not present in this case.

Also, can anyone shed some light on why CSRF attack protection is needed here anyway? Is there any other way to obtain the session without by-passing the CSRF validation?

**Comment by SammyK** [comment]
Yes, in version 4.0 if the `state` param for CSRF is missing, `getSession()` will return `null`. In the next version it will throw an exception if the param is missing or does not match the expected value.

So we'd need to look into this issue of there not being a `state` param on mobile.

@ayushchd How are you initiating the login process for mobile people?

**Comment by ayushchd** [comment]
@SammyK I ended up putting up the Login button. Basically, although I had the session already, I had to ask them to login again.

**Comment by SammyK** [comment]
Yeah, that's a good way to do it. That way you always get a fresh access token to work with. Glad you figured it out! :)

**Comment by ayushchd** [comment]
True, but it is redundant. I think there shouldn't be a check on the `state` param when redirecting to the application's mobile URL or probably some other way around to let you access the session that is already set during mobile redirection.
