### ISSUE TITLE
getRawSignedRequestFromGet ?

### ISSUE THREAD

**Issue by ManuelHanisch** [facebook/facebook-php-sdk-v4#277]
Hello guys,
i am rewriting my app to use your PHP SDK. 
When i am sending data with POST, unfortunatelly my app appends the signed_request to the URL in a lot of cases. 

Now, the FacebookCanvasLoginHelper::getRawSignedRequest function only checks 
for POST data

$rawSignedRequest = $this->getRawSignedRequestFromPost(); 

The function getRawSignedRequestFromGet() exists, but is never used inside the SDK.

Of course i can put my signed_request into the POST variable and problem is solved.
But i want to ask if its possible to add this into the SDK ?  like this:

$rawSignedRequest = $this->getRawSignedRequestFromPost(); 
if(!isset($rawSignedRequest)) $rawSignedRequest = $this->getRawSignedRequestFromGet();

or do i miss something? 

best regards, 
Manuel

**Comment by SammyK** [comment]
Hey @ManuelHanisch! This method will be completely removed in the next version per #336.

If you need to decode a signed request, you can just use the `Facebook\SignedRequest` entity directly in the next version release:

```php
$app = $fb->getApp();
$sr = new Facebook\SignedRequest($app, $_GET['signed_request']);
```

**Comment by ManuelHanisch** [comment]
Alright, thanks!  You are doing a great job guys!

**Comment by SammyK** [comment]
Thanks @ManuelHanisch! :)
