### ISSUE TITLE
get feed list of posts with pagination ?

### ISSUE THREAD

**Issue by christhomas** [facebook/facebook-php-sdk-v4#282]
I've got a problem and whilst this isn't specifically a facebook api problem, it's a general problem with people trying to implement REST like interfaces, it's basically that I think REST is mostly a lie and that actually RPC mechanisms are what people actually end up implementing. GET with parameters? putting them in the header? thats called cheating... Just use RPC and have done with it.

Alas I digress... When obtaining a list of posts from a page, I have to use the GET method, however, in order to support pagination, I have to supply "limit", "until", or other parameters.

So, if I'm getting, the facebook API as it stands does not allow me to send arguments to the get request, however I obviously need to post the pagination parameters.  Therefore I thought ok, instead of using get(), I'll use post(), except I can't because the method doesn't support it and throws an exception.

So basically the only way I can find to get around this problem is to modify the Facebook::get() method to accept an params array and pass it instead of using $params = [], I've looked through the rest of the API and I can't find anything that can help me.

So, I modified the method like so, now I can obtain the list of posts from a facebook page, how are you guys doing this right now? I suppose you don't just test the code that it does what it's supposed, but you test use-cases as well? I've taken a brief look and I didnt find them, so I think you guys are programming to a set defined of interfaces as opposed to looking at how they are supposed to be used and realising that the API doesn't do things which are commonly done in using the API.

So, I modified Facebook.php like so:

    public function get(
        $endpoint,
        array $params = [],
        $accessToken = null,
        $eTag = null,
        $graphVersion = null)
    {
        return $this->sendRequest(
            'GET',
            $endpoint,
            $params,
            $accessToken,
            $eTag,
            $graphVersion);
    }

**Comment by SammyK** [comment]
@gfosco - this can be closed because it's a PR now: #307
