### ISSUE TITLE
[4.1] Final BC's before release & docs

### ISSUE THREAD

**Issue by SammyK** [facebook/facebook-php-sdk-v4#290]
Hey guys! We're really close to being able to release 4.1! At this point it's mainly just updating the docs and a few other BC's I wanted to discuss.

1. As mentioned in #286, any exceptions that deal with error responses from the Graph API should be renamed for greater clarity. Right now it's not clear what the `FacebookOtherException` is, but it's thrown when an unknown error response is received from Graph.  I propose renaming `Facebook*Exception`'s for Graph error responses to `GraphError*Exception`.  So `FacebookOtherException` would become `GraphErrorOtherException` for example.
2. I'd like to kill the `Entities` folder which is the only folder left that describes the programming method vs the behavior. To kill this we'll need to move `AccessToken`, `FacebookApp` & `SignedRequest` to the root `src/` folder. Then we'd move `FacebookRequest`, `FacebookResponse`, `FacebookBatchRequest`, & `FacebookBatchResponse` to the `Http` folder.
3. After #280 and #287 get merged in, I'd like to refactor access token handling by crating an `AccessTokenFactory` that handles the `FacebookApp` & `FacebookClient` dependencies to create new `AccessToken`'s. It should make handling access tokens much easier - especially within the context of the helpers.

Those are the last 3 BC's that have been bugging me. After that it's all docs baby! Since the docs have been updated along the way, it's not 100% clear what needs to be updated. After scanning the code, here's a master TODO list to knock out the docs:

- [x] `FacebookApp` needs docs (will be affected by BC no. 2)
- [x] `FacebookRequest` docs need updating (will be affected by BC no. 2)
- [x] `FacebookResponse` docs need updating (will be affected by BC no. 2)
- [x] `FacebookBatchRequest` needs docs (will be affected by BC no. 2)
- [x] `FacebookBatchResponse` needs docs (will be affected by BC no. 2)
- [x] `SignedRequest` needs docs (will be affected by BC no. 2)
- [ ] `FacebookResponseException` docs need updating (will be affected by BC no. 1)
- [x] `FacebookSDKException` needs docs
- [x] `GraphObject` needs to verify all getters are documented, needs `GraphPage`, `GraphAlbum` documentation. Also needs to mention auto-casting.
- [ ] `FacebookCanvasHelper` docs need updating (will be affected by BC no. 3)
- [ ] `FacebookJavaScriptHelper` docs need updating (will be affected by BC no. 3)
- [ ] `FacebookPageTabHelper` docs need updating (will be affected by BC no. 3)
- [ ] `FacebookRedirectLoginHelper` docs need updating (will be affected by BC no. 3)
- [ ] `FacebookHttpClientInterface` needs docs (should explain peer-verification a bit), (example in docs will change pending BC no. 3)
- [ ] `PersistentDataInterface` (example in docs will change pending BC no. 3)
- [ ] `UrlDetectionInterface` (example in docs will change pending BC no. 3)
- [x] `FacebookClient` needs docs
- [ ] `AccessToken` needs docs (will be affected by BC no. 3 with `AccessTokenFactory`)
- [ ] `sdk_getting_started.fbmd` needs updating after all BC's discussed
- [x] `FacebookSession.fbmd` can be killed
- [x] `retrieve_user_profile.fbmd` docs needs updating
- [ ] `sdk_downloads.fbmd` needs to be updated with latest version numbers
- [ ] `sdk_landing_page.fbmd` needs to link to new examples
- [ ] `sdk_reference.fbmd` Will need to be updated after all the BC's above
- [x] `upload_photo.fbmd` docs needs updating
- [ ] `upload_video.fbmd` needs docs
- [ ] `batch_example.fbmd` needs docs
- [ ] `batch_upload_photo.fbmd` needs docs
- [ ] `batch_upload_video.fbmd` needs docs
- [ ] `pagination.fbmd` needs docs
- [ ] `CHANGELOG.md` needs to be updated

That should be it - let me know if I missed anything! I'll get started on some of these that don't have dependency PR's or proposed BC's. :)

And I've got a bunch of examples I'd like to add to an `examples/` folder in the repo that should give developers enough boilerplate to do some of the most common tasks with the SDK. But I'll wait on those until we discuss the 3 BC's above. :)

**Comment by stevenmaguire** [comment]
I like what you guys are doing here.
