### ISSUE TITLE
Permision Error

### ISSUE THREAD

**Issue by saruman** [facebook/facebook-php-sdk-v4#302]
Hi.
From last Monday, I don't be able to post into my FB page using the PHP SDK.   The scripts works for 4 days in a row, and after that, an error message shows the with the problem:

Facebook\FacebookPermissionException [ 200 ]: (#200) Permissions error
Facebook/FacebookRequestException.php (line 128)

// Missing Permissions
127     if ($code == 10 || ($code >= 200 && $code <= 299)) {
128       return new FacebookPermissionException($raw, $data, $statusCode);
129     }

I have the latest version of the SDK: 4.0.13.

The token never expire and has this scopes:
public_profile, basic_info, read_stream, email, read_friendlists, manage_pages, publish_actions, user_birthday, user_hometown, user_website, user_friends, user_about_me

If I execute the same POST into the facebook Graph Tool works and the publication shows up on my facebook feed, but not with my script that was working some days before.

Let me know.

**Comment by codex8** [comment]
Try this include the publish_actions permission in your Page Access Token (see https://developers.facebook.com/docs/graph-api/reference/v2.0/page/feed/#publish)? Then you should be able to use this token also to post to the Page's wall.

**Comment by SammyK** [comment]
Can you provide the section of code that's throwing the exception?

**Comment by SammyK** [comment]
@gfosco This can close

@saruman If you're still having trouble let us know!

**Comment by saruman** [comment]
@SammyK No. It's working now perfectly.  Every day I checked and my script is working perfectly :) thank you.

**Comment by SammyK** [comment]
Glad it's working for you @saruman! :)
