### ISSUE TITLE
Facebook PageTab App getSession issue

### ISSUE THREAD

**Issue by sholeem** [facebook/facebook-php-sdk-v4#306]
Hi all,
excuse me if this issue was already explained somewhere, but I can't seem to find any answer online.

I'm building Facebook Page Tab App, and I'm having trouble to retrieve session for user.
I'm doing this with Laravel 4.2 and Facebook php sdk 4.0.

I required sdk using Composer, and this is what I have in my composer.json file : "facebook/php-sdk-v4": "~4.0.12". 

In my controller , I have something like this:

        FacebookSession::setDefaultApplication('app-id', 'app-secret');

        $helper = new FacebookPageTabHelper();
        $session = $helper->getSession();

        $user = (new FacebookRequest($session, 'GET', '/me'))->execute()->getGraphObject(GraphUser::className());

        $userName = $user->getName();

        return $userName;

The error I'm getting is : Argument 1 passed to Facebook\FacebookRequest::__construct() must be an instance of Facebook\FacebookSession, null given

Everything worked when first accessed app, but after session had expired I couldn't find solution of retrieving it.

Any help would be appreciated.

Tnx

**Comment by SammyK** [comment]
This line:

```php
$session = $helper->getSession();
```

Is returning `null` since a signed request with a `code` or `access_token` could not be found. If `$session` is null, you should present a "login with facebook" link to the user.

@gfosco This can be closed. :)
