### ISSUE TITLE
Facebook API error on Safari version 5 but works fine on Chrome and Firefox … any feedback

### ISSUE THREAD

**Issue by mase857** [facebook/facebook-php-sdk-v4#313]
Here's the error that I get on Safari version 5  when trying to log in through facebook and get user info . The error is below .

string '{"error":{"message":"An active access token must be used to query information about the current user.","type":"OAuthException","code":2500}}' (length=140)

I'm sure this looks familiar , but it only happens when i use Safari 5 , it works on other safari versions and browsers .. The relevant code that generate this error is this one

$user_profile = $facebookAPI->getUser(); 

// User function is below

    function getUser(){
        $user_profile = ''; 
        if($this->facebookSession) {
          $access_token = $this->facebookSession->getToken(); 
          try {
            $request = new Facebook\FacebookRequest($this->facebookSession, 'GET', '/me',array(
            'access_token' => $access_token));
            $user_profile = $request->execute()->getGraphObject(Facebook\GraphUser::className()); 
          } catch(FacebookRequestException $ex) {
            systemError("Exception occured getting facebook user, with message: " . $ex->getMessage());
          }
        }

        return $user_profile;
    }

/  And the part that actually returns the error is the execute function execute() above

   * @return FacebookResponse
   *
   * @throws FacebookSDKException
   * @throws FacebookRequestException
   */
  public function execute()
  {
    $url = $this->getRequestURL(); 
    $params = $this->getParameters();

    if ($this->method === "GET") {
      $url = self::appendParamsToUrl($url, $params);
      $params = array();
    }

    $connection = self::getHttpClientHandler();
    $connection->addRequestHeader('User-Agent', 'fb-php-' . self::VERSION);
    $connection->addRequestHeader('Accept-Encoding', '*'); // Support all available encodings.

    // ETag
    if (isset($this->etag)) {
      $connection->addRequestHeader('If-None-Match', $this->etag);
    }

    // Should throw `FacebookSDKException` exception on HTTP client error.
    // Don't catch to allow it to bubble up.
    $result = $connection->send($url, $this->method, $params);  var_dump($result); exit;

    static::$requestCount++;

    $etagHit = 304 == $connection->getResponseHttpStatusCode();

    $headers = $connection->getResponseHeaders();
    $etagReceived = isset($headers['ETag']) ? $headers['ETag'] : null;

    $decodedResult = json_decode($result);
    if ($decodedResult === null) {
      $out = array();
      parse_str($result, $out);
      return new FacebookResponse($this, $out, $result, $etagHit, $etagReceived);
    }
    if (isset($decodedResult->error)) {
      throw FacebookRequestException::create(
        $result,
        $decodedResult->error,
        $connection->getResponseHttpStatusCode()
      );
    }

    return new FacebookResponse($this, $decodedResult, $result, $etagHit, $etagReceived);
  }

[/CODE]
What would really be causing this ? it works on Firefox , Chrome ...and on the iPhone , but Safari 5 throws that error ... Your feedback would be soo much appreciated man.

**Comment by gfosco** [comment]
Can you log the session / access token and ensure it's valid?  It really shouldn't matter what browser you're using.

**Comment by SammyK** [comment]
You don't need to explicitly pass `'access_token' => $access_token` to `Facebook\FacebookRequest`. That is done via `$this->facebookSession`.

@gfosco This can close.

@mase857 If you're still having trouble with this, let us know!
