### ISSUE TITLE
Handle if access token is passed in the $path variable to FacebookRequest

### ISSUE THREAD

**Issue by WizKid** [facebook/facebook-php-sdk-v4#317]
If access token is passed in the $params we handle it to use it for appsecret_proof. But if is passed in the path it is not.

The easiest would just be to forbid any query parameters in the path so people have to use the $params. If not we need to parse the path and check for the access token there also.

**Comment by IvoPereira** [comment]
+1 on this. I would not say to forbid it, but access token in the path should override the access token provided with request.

**Comment by WizKid** [comment]
The reason I suggested to forbid it is that allowing 3 different ways to pass the access token is a sure sign it something will break in the future. I would even suggest making it not allowed to pass through $params and force you to use FacebookSession. That way there would only be one way to pass the session and less risk of bugs

**Comment by SammyK** [comment]
Is this for 4.0 or 4.1?

In 4.1, the params from the path are [parsed for the access token](https://github.com/facebook/facebook-php-sdk-v4/blob/master/src/Facebook/FacebookRequest.php#L278) (and later an appsecret_proof is generated from it).

**Comment by WizKid** [comment]
Sorry. You are right. This was in 4.0. You can close it
