### ISSUE TITLE
[4.1] No thumbnail in some posts

### ISSUE THREAD

**Issue by gbhrdt** [facebook/facebook-php-sdk-v4#318]
Hi,
I'm using a multiple FacebookBatchRequest (each is holding up to 50 FacebookRequests) to automatically post to Facebook pages via cronjobs.

```php

// mysql stuff...
// ...

$requests = array();
$requests[] = new FacebookRequest(
    $fb->getApp(),
    $accessToken,
    'POST',
    '/' . $page->page_id . '/feed',
    array (
    	'link' => $this->option('link'),
    	'message' => $this->option('message'),
    )
);

// chunk requests into arrays of 50 (batch request limit)
$requests = array_chunk($requests, 50);
foreach ($requests as $requestsChunk) {
	try 
	{
		$response = $fb->sendBatchRequest($requestsChunk, $requestsChunk[0]->getAccessToken());
	}
	catch (FacebookResponseException $e)
	{
		if ($e->getPrevious() instanceof FacebookAuthorizationException)
		{
			$this->error('Invalid access token');
		}
		else
		{
			//
		}
	}
}
```

Most of the time, everything goes well and Facebook recoginzes the thumbnail picture from the site's `og:image` tag (which is always present: https://puu.sh/emDSL/8f242cf531.png).
But sometimes, Facebook just gives me something like this: https://puu.sh/emDQn/7802f70a5e.png.
How can this be? I'm always posting arcticles from the excact same wordpress site, and also using URLs which do not have any redirects. The issue doesn't occur on particular articles or times, it's just random.

This may not be the issue of this SDK (I'm using v4.1, latest commit), but I hope you can help me.

**Comment by roman02** [comment]
This has sometimes happened to me even when I posted **manually** on Facebook.com.

**Comment by SammyK** [comment]
I don't think this is an SDK issue. This just happens sometimes with Facebook's open graph tag scrapper. You can force Facebook to re-scrape a URL using the [debugger tool](https://developers.facebook.com/tools/debug/).

**Comment by roman02** [comment]
What I described happened to me recently even **after** rescraping.

**Comment by roman02** [comment]
I've just had this problem again. I had to request re-scraping 3 or 4 times before the scraper actually got my image. At first, it kept complaining that it was too small or absent.

**Comment by gbhrdt** [comment]
That's very weird. The Facebook enigeers should definetely fix that!

**Comment by SammyK** [comment]
Yeah, this sketch behavior is not SDK related. But could be a bug so you can [submit bug report for it here](https://developers.facebook.com/bugs/).

@gfosco This can close.
