### ISSUE TITLE
Q: Why this version of the SDK requires PHP 5.4?

### ISSUE THREAD

**Issue by rvarbanov** [facebook/facebook-php-sdk-v4#319]
Why this version of the SDK requires PHP 5.4?

> This version of the Facebook SDK for PHP requires PHP 5.4 or greater.

We are currently running PHP 5.3 on our servers and to request an upgrade I need to be able to say why is the upgrade needed.

**Comment by yguedidi** [comment]
- PHP 5.3 reached end of life, it's not supported anymore
- security fixes
- optionally: 5.4 new features

**Comment by SammyK** [comment]
What @yguedidi said! :)

Also check out [Anthony Ferrara](https://twitter.com/ircmaxell)'s excellent article on [PHP version requirements](http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html). Hopefully that'll help you out when you request an upgrade. Good luck!

**Comment by rvarbanov** [comment]
I agree with you @SammyK and @yguedidi,
but my question was more of the lines of, what 5.4 features does the new SDK uses that are not in 5.3

**Comment by SammyK** [comment]
Of the [5.4 features](http://php.net/manual/en/migration54.new-features.php), the SDK makes use of:

- [Traits](https://github.com/facebook/facebook-php-sdk-v4/blob/master/src/Facebook/PseudoRandomString/PseudoRandomStringGeneratorTrait.php)
- [Short-array syntax](https://github.com/facebook/facebook-php-sdk-v4/blob/master/src/Facebook/Facebook.php#L374)
- In v4.0 there was [class member access on instantiation](https://github.com/facebook/facebook-php-sdk-v4/blob/88af90d80923cd72ea7201da088ec4e9b21e42b6/src/Facebook/FacebookRedirectLoginHelper.php#L180) but v4.1 does not make use of that.

I think that's it. :)

**Comment by rvarbanov** [comment]
Thank you very much, @SammyK

**Comment by yguedidi** [comment]
@rvarbanov if in 2015 your hosting service requires more than security and performance as reasons to upgrade PHP, switch to an other one haha :)

**Comment by rvarbanov** [comment]
@yguedidi, we are past that issue :) but to give you more information, we are on self-managed server...

**Comment by yguedidi** [comment]
@gfosco can be closed
