### ISSUE TITLE
[6.0] [Proposal] Rename GraphObject & GraphList

### ISSUE THREAD

**Issue by SammyK** [facebook/facebook-php-sdk-v4#320]
After discussing the Facebook PHP SDK a bit on the [domain-driven design discussion on the PHP Roundtable](https://www.phproundtable.com/episode/domain-driven-design-in-php), I realized that there are a few places in the SDK where we could better be in sync with Facebook nomenclature.

The two biggest DDD-eye-sores are the naming `GraphObject` & `GraphList`.

1. The `GraphObject` represents a "thing" on the Graph API. ["Things" in Graph are called "nodes"](https://developers.facebook.com/docs/graph-api/quickstart/v2.2#basics). We started going the right direction by renaming the containing folder to `GraphNodes` but let's go ahead and complete that by renaming `GraphObject` to `GraphNode`.
2. Relationships between nodes in Graph [are called "edges"](https://developers.facebook.com/docs/graph-api/quickstart/v2.2#basics).The `GraphList` represents one or more nodes returned by Graph from an edge. I recommend we rename `GraphList` to `GraphEdge`.

This change will disambiguate what these objects represent and reduce confusion when someone is reading through the Graph API and Facebook SDK documentation. :)

**Comment by yguedidi** [comment]
:+1:

**Comment by yguedidi** [comment]
@SammyK as we discuted in #323, edges, like the picture one, are not always lists...

**Comment by SammyK** [comment]
Yep! One more reason to rename it to `GraphEdge`. :)

**Comment by SammyK** [comment]
Another way of thinking about this is that edges describe relationships between nodes. In some cases that relationship will always be between a node and one-and-only-one other node.

@gfosco In an effort to make the SDK more DDD-focused, do you know (or someone from the Graph API knows) if there is a name to describe an edge that will always return one-and-only one node? Like in the `user/picture` example?

**Comment by gfosco** [comment]
They are just called edges, doesn't appear to be any specific language around an edge that only returns one node.  I support the renaming.

**Comment by SammyK** [comment]
Sounds good! Changed the title to slate this for 4.2 :)

**Comment by yguedidi** [comment]
I think there is a simple solution:
- keep `{id}/picture` that will always redirect to the picture. Nor a node, nor an edge, just a shortcut to the picture when you got the id.
- add a `picture` field to the node that will represent the actual object we get with `?redirect=false`

Thoughts?

**Comment by SammyK** [comment]
Yeah, that sounds good!

**Comment by argb** [comment]
support renaming

**Comment by SammyK** [comment]
Closed via #423.

**Comment by devmsh** [comment]
mmm

What about `$graphObjectMap` ?

**Comment by SammyK** [comment]
Yeah I wasn't able to figure out how to change that in a non BC way. So I think we should slate renaming it to `$graphNodeMap` in v6.
