### ISSUE TITLE
Q: Is there a "Upgrading from v3 to v4" guide?

### ISSUE THREAD

**Issue by rvarbanov** [facebook/facebook-php-sdk-v4#321]
Are there any docs that outline what needs to be done to upgrade my code from v3 to v4 of the SDK?

I am looking for something similar to the [JavaScript SDK guide](https://developers.facebook.com/docs/apps/upgrading#v1tov2)

**Comment by SammyK** [comment]
There isn't but that's a good idea for a blog post! :)

**Comment by rvarbanov** [comment]
Go for it :)

I was just reading your other post: [Best practice for Facebook login flow with the JavaScript SDK and PHP SDK v4.1](https://www.sammyk.me/best-practice-for-facebook-login-with-the-javascript-sdk-and-php-sdk-v4-1)

**Comment by SammyK** [comment]
Yay! :)

I'm guessing within a month or two for 4.1 release.

**Comment by yguedidi** [comment]
And maybe a guide from v4.0 to v4.1

**Comment by SammyK** [comment]
Good idea!

**Comment by SammyK** [comment]
@gfosco  This can close. :)
