### ISSUE TITLE
Installing via composer with the example install config results in an Invalid Argument Exception

### ISSUE THREAD

**Issue by r3wt** [facebook/facebook-php-sdk-v4#322]
so instead i installed with the following command

```
composer require "facebook/php-sdk-v4" @stable
```

**Comment by SammyK** [comment]
What was the original command you used that caused the error? If your [default `minimum-stability` option is set to `dev` in composer](https://getcomposer.org/doc/04-schema.md#minimum-stability) then you'll be pulling in `dev-master` which is the development branch.
