### ISSUE TITLE
FacebookCurlHttpClient's call of init() steps on curl opts set manually

### ISSUE THREAD

**Issue by jkrasnoo** [facebook/facebook-php-sdk-v4#327]
Hey all,
In FacebookCurlHttpClient the function openConnection has a call to FacebookCurl's init() before setting options. If a programmer sets a custom FacebookCurl instance within his instantiated client that call to init() will step on that custom FacebookCurl by creating a new handle. The init function doesn't check to see if a handle has already been created.

I needed a custom handle since there really is no other way to implement the proxy settings required to make a connection. Going through the code there is no way to set a proxy for a request. The fix for this is simple and I'll be submitting a pull request.

**Comment by gfosco** [comment]
Assuming this was covered by your PR #328 

Thanks!
