### ISSUE TITLE
Exception API broken with FacebookRequestException

### ISSUE THREAD

**Issue by pugsley** [facebook/facebook-php-sdk-v4#329]
I'm writing unit tests with Mockery to simulate Facebook SDK exceptions. However, the `FacebookRequestException` class breaks the PHP `Exception` API with the following constructor:

```
public function __construct($rawResponse, $responseData, $statusCode)
```

The standard Exception constructor looks like this:
```
public function __construct($message = "", $code = 0, Exception $previous = null) { }
```

This makes it especially hard to write test cases as I'm having to write an exception class wrapper that extends `FacebookRequestException`, corrects the constructor API then recalls `FacebookRequestException->__construct` = yuck! Maybe FacebookRequestException could be created in a factory or receive the extra parameters as a 4th parameter.

**Comment by pugsley** [comment]
Actually, I can't even write a wrapper because the `$statusCode`, `$rawResponse` & `$responseData` vars are `private`. Why not make them `protected`?

**Comment by pugsley** [comment]
I've managed to hack around it for now with the following:

```
use Facebook\FacebookAuthorizationException;

class FacebookAuthorizationExceptionTest extends FacebookAuthorizationException {
    public function __construct($message, $code, Exception $previous = null)
    {
        parent::__construct($message, "{}", $code);
    }
}
```
Potentially nothing to see here.

**Comment by SammyK** [comment]
Hey @pugsley! Great points! Would you like to submit a PR to fix this? Or I can put it on the "TODO" list and hopefully someone can knock it out for v4.1 a least. :)

**Comment by SammyK** [comment]
Let's consider this after the next stable tag release.

**Comment by pugsley** [comment]
Sounds good, if I have some time after that I'll see what I can do.

**Comment by yguedidi** [comment]
>  to simulate Facebook SDK exceptions.

What do you mean here? Why constructor parameters should be same as `Exception` ones?
