### ISSUE TITLE
[Proposal] Revisit PSR-2 compliancy

### ISSUE THREAD

**Issue by SammyK** [facebook/facebook-php-sdk-v4#331]
I wanted to revisit something @yguedidi brought up a while ago in #27, [PSR-2 compliancy](http://www.php-fig.org/psr/psr-2/).

Although PSR-2 isn't mission critical, it would be an excellent entry point for new people to start contributing to the SDK.

The Chicago PHP UG is hosting an [open source workshop](http://www.meetup.com/Chicago-PHP-User-Group/events/219902483/) in a few weeks. And since I've been asked about contributing to the PHP SDK by several developers here in Chicago (ping @stevenmaguire, @nickescobedo, et al), I'm going to be getting a little group together at the workshop to start contributing to the PHP SDK. 

I'm my last refactor I was making a laundry list of things (18 items so far!) people could contribute to the SDK. And one of those is PSR-2 compliancy. It's low hanging fruit and would really instill a sense of ownership to new contributors. But we just need the blessing from @gfosco :)

**Comment by yguedidi** [comment]
@SammyK I'm of course :+1:!
But in fact it's impossible... Facebook have there own coding standard ([ref in HHVM](https://github.com/facebook/hhvm/blob/master/hphp/doc/coding-conventions.md#general-rules))

**Comment by SammyK** [comment]
True, but that's for HHVM. I doubt that's a company-wide policy. :)

PS: Did you know that PHP internals uses tabs instead of spaces? Cray!

![](http://i.imgur.com/IW8simF.gif)

**Comment by nickescobedo** [comment]
:thumbsup:

**Comment by yguedidi** [comment]
I think it's a company-wide policy, and I hope we can use PSR-2 here :)

**Comment by gfosco** [comment]
You have my blessing.  Do we really need to use 4 spaces?  That's the ONLY thing I don't agree with.

**Comment by SammyK** [comment]
Unfortunately it's [bullet point no 2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#1-overview). :/

So would it still be blessed by @gfosco holy water? :)

**Comment by gfosco** [comment]
Sigh.............  Okay.

**Comment by SammyK** [comment]
![](http://media.giphy.com/media/Tk1RH495RjYYM/giphy.gif)

@philsturgeon would be so proud of Facebook! :)

**Comment by yguedidi** [comment]
Houray!

**Comment by stevenmaguire** [comment]
![everybody dance](http://axisofstevil.s3.amazonaws.com/stuff/zoidberg.gif)

**Comment by philsturgeon** [comment]
Closed because implemented or closed because wontfix?

**Comment by SammyK** [comment]
Lol - closed because it's gonna be implemented in #356 :)

**Comment by gfosco** [comment]
Oh, sorry, we can keep this open until it is completed.

**Comment by philsturgeon** [comment]
No worries on that, so long as a trail of issues or PRs is there for a) folks interested in subscribing and b) history. 

You can close now a new issue is covering it.

**Comment by yguedidi** [comment]
#356 updated.
