### ISSUE TITLE
[Proposal] Revisit Semantic Versioning

### ISSUE THREAD

**Issue by SammyK** [facebook/facebook-php-sdk-v4#332]
I'm proposing we revisit yet another @yguedidi issue from a while ago #134, [Semantic Versioning](http://semver.org/).

# The problem

Currently we're handling versioning like this: `4.MAJOR.MINOR|PATCH`. Both `MINOR` and `PATCH` should be backwards-compatible and `MAJOR` can contain breaking changes.

We're running into an issue like in #326 where simply changing the default Graph version will actually break BC. And updating the SDK to fit the new Graph API version (like removing `isLiked()` from `FacebookPageTabHelper`) is another BC.

And as the SDK evolves and starts to conform more to a [ubiquitous language](http://martinfowler.com/bliki/UbiquitousLanguage.html) within Facebook's domain, these smaller name changes are often BC's as well.

Another issue that could possibly explode when we tag 4.1 stable relates to issue #268. For those who have a composer requiring `~4.0` will get the super-breaking-change from 4.0 to 4.1 as soon as 4.1 is tagged. My own `composer.json`'s were set up this way until a few months ago.

# The solution

So it'd be really nice to follow SemVer's `MAJOR.MINOR.PATCH` format. And we could follow this versioning schedule:

## MAJOR

- When a new version of Graph is released.
- Any SDK API breaking changes related to ubiquitous language or breaking refactors.

We could hold off on releasing any breaking API changes until the next Graph API version. So the SDK would follow the same versioning schedule as Graph.

## MINOR

- Any new feature that doesn't break BC.

## PATCH

- Non-breaking bug fixes.
- Non-breaking security updates.

# Going forward

If we follow this setup, all these huge refactors on `dev-master` would be tagged as `5.0.0` instead of `4.1.0`. Then with the next Graph version we'd roll any breaking changes on `dev-master` into `6.0.0`.

This will also help us make a very easy-to-understand `UPGRADE-5.0.md`, `UPGRADE-6.0.md` files (as pointed out is something missing from the docs in #321).

# Considerations

The `-v4` suffix in the repo name needs to be addressed but I'm not 100% sure how to approach that one.

Thoughts? :)

**Comment by yguedidi** [comment]
> When a new version of Graph is released.

I think this should go in the minor part. To make this possible, I think the SDK default Graph API version should be null, ie unversionned.
Then we can add new fields/nodes as new method/obects, depecate fields/node that are not part of the last Graph version. And when the default unversionned Graph API version change, we can release a new SDK major version that remove deprecated things.

I don't know, if I'm understandable, I'm writing this quickly.. :)

**Comment by SammyK** [comment]
> I think the SDK default Graph API version should be null

I agree - it should be up to the developer to upgrade the version of Graph. And I have a note to myself when I start going balls-to-the-wall on the docs to stress that defining the Graph version on instantiation is crucial (like how the JS SDK does).

> And when the default unversionned Graph API version change, we can release a new SDK major version that remove deprecated things.

Sounds good. As a general rule to keep track of this, we should use a combo of the `@deprecated` docblock tag and a `@todo` flag that tracks the date it should be removed.

For example:

```php
class FacebookPageTabHelper extends FacebookCanvasHelper
{
  // . . .
  /**
   * Returns true if the page is liked by the user.
   *
   * @return boolean
   *
   * @deprecated Graph v2.1: The liked field will no longer be returned
   *             in the page property of the signed_request object for Page Tab apps
   *             https://developers.facebook.com/blog/post/2014/08/07/Graph-API-v2.1/
   * @todo Remove after November 5, 2014
   */
  public function isLiked()
  {
    return $this->getPageData('liked') === true;
  }
}
```

**Comment by yguedidi** [comment]
:+1: about the combo!

**Comment by gfosco** [comment]
I'm pretty set on this SDK being 4.x forever, until someone decides to re-write it again...

**Comment by SammyK** [comment]
That's cool - we can still roll with this launch schedule using the second number as `MAJOR`. :)

**Comment by yguedidi** [comment]
@gfosco I'll (re)write my own SDK with Modelling by Exemples, DDD, BDD, to learn and apply some good practices! :)
Unfortunatly I don't have much time, but I hope I'll find soon!

**Comment by yguedidi** [comment]
Sorry for make you wait @SammyK and @gfosco haha

**Comment by SammyK** [comment]
:+1:
