### ISSUE TITLE
Clarity needed on requirements for usage of the FacebookRedirectLoginHelper class

### ISSUE THREAD

**Issue by stevenmaguire** [facebook/facebook-php-sdk-v4#333]
I am getting up to speed on the current state of the project and when running the test suite straight away I notice one test is failing. 

```shell
1) Facebook\Tests\Helpers\FacebookRedirectLoginHelperTest::testLoginURL
Unexpected base login URL returned from getLoginUrl().
Failed asserting that false is true.
```

Digging into the code a bit, the test method appears to be using a different method signature than the perceived functionality of the implementation.

```php
class FacebookRedirectLoginHelperTest
{
    //
    public function testLoginURL()
    {
        //
        $helper = new FacebookRedirectLoginHelper($app, $this->persistentDataHandler);
        $scope = ['foo','bar'];
        $loginUrl = $helper->getLoginUrl(self::REDIRECT_URL, $scope, true, 'v1337');
        //
    }
    //
}

class FacebookRedirectLoginHelper
{
    //
    public function getLoginUrl($redirectUrl, array $scope = [], $version = null, $separator = '&')
    {
       return $this->makeUrl($redirectUrl, $scope, $version, $separator);
    }
    //
}
```

The documentation indicates usage that disagrees with both the test and the implementation:

https://github.com/facebook/facebook-php-sdk-v4/blob/master/docs/FacebookRedirectLoginHelper.fbmd
```php
$helper = new FacebookRedirectLoginHelper($redirect_url, $appId = NULL, $appSecret = NULL);
echo '<a href="' . $helper->getLoginUrl() . '">Login with Facebook</a>';
```

What is the expected usage of this method? 

If we can clearly define this, I am happy to clean up the tests and the implementation to ensure this functions as expected.

**Comment by stevenmaguire** [comment]
@SammyK I would of course love your input here :)

**Comment by SammyK** [comment]
Nice find @stevenmaguire! That was a failing test that somehow snuck in from a recent login URL refactor. I actually fixed it in #330 so once that's merged all tests should pass. :)

**Comment by SammyK** [comment]
Oh, and the docs haven't been completely updated for 4.1 yet. Just waiting on a few more pending BC's. :)

**Comment by stevenmaguire** [comment]
Oh good! I will just proceed with some of the other enhancements, treating this as a known defect.
