### ISSUE TITLE
[4.1] Scrutinizer-CI

### ISSUE THREAD

**Issue by yguedidi** [facebook/facebook-php-sdk-v4#342]
@gfosco I'll encourage you to use [Scrutinizer-CI](https://scrutinizer-ci.com/) with this repo, on the master branch.

Just login with your GitHub account, and configure some analysis checks, coding style and more. It will give us a good report of some thing we can work on before releasing 4.1.

I suggest to at least configure [PHP Code Sniffer](https://scrutinizer-ci.com/docs/tools/php/code-sniffer/) and [PHP CS Fixer](https://scrutinizer-ci.com/docs/tools/php/cs-fixer/) with the PSR-2 level.

You can also fine configure many other checks.

**Comment by SammyK** [comment]
We can do a PSR-2 check with Code Sniffer using Travis-CI too. :) But I wouldn't hold up on 4.1 release for PSR-2.

**Comment by yguedidi** [comment]
Sure, but scrutinizer is dedicated to code analysis.
Not only with PHP Code Sniffer, but with many other tools and many other checks (bugs, security, code duplication, etc...).
And all that things in a pretty interface with useful reports :)

**Comment by SammyK** [comment]
Cool! Never used it but it looks cool. :)

**Comment by yguedidi** [comment]
Just try it with one of your project, you'll see how it's awsome hehe

**Comment by SammyK** [comment]
Do they have a free version for open source projects like Travis-CI? It seems like everything costs some $$.

**Comment by yguedidi** [comment]
Like Travis-CI, it's free for open source projects ;)

**Comment by gfosco** [comment]
I added Scrutinizer to the repo, for the master branch.

**Comment by SammyK** [comment]
:+1:

**Comment by yguedidi** [comment]
:+1: 

@gfosco maybe you can configure which conding style you want thanks to Scrutinizer-CI now.
Some new questions:
- spaces arround concatenation (my personal thought: :-1:)
- space after negate `!` (I'm :-1: too)
- space after casting (:-1:)
- quotes (single one for me)
- ...
