### ISSUE TITLE
Call fails with unknown error - works fine in FB graph tool

### ISSUE THREAD

**Issue by nsanden** [facebook/facebook-php-sdk-v4#370]
FAILS using FacebookRequest()
WORKS using FB graph explorer
/search?type=page&q=great+danes&fields=name,likes,picture,talking_about_count

WORKS in both
/search?type=page&q=danes&fields=name,likes,picture,talking_about_count

**Comment by gfosco** [comment]
Can you provide the code you're using to build this with FacebookRequest?

**Comment by nsanden** [comment]
I thought so too but i've double checked that. I'm just sending a straight call now, not through form or url or anything.

```php
$graph = '/search?type=page&q=great+danes&fields=name,likes,picture,talking_about_count';
echo $graph;
$r = (new FacebookRequest( $this->_session, 'GET', $graph, []))->execute()->getGraphObject()->asArray();
echo "<pre>";
print_r($r);
echo "</pre>";
die();
```
which results in:
```
/search?type=page&q=great+danes&fields=name,likes,picture,talking_about_count
Array
(
    [error_code] => 1
    [error_msg] => An unknown error occurred
)
```

Again, exact same code works when I change it to just "danes" for $q

**Comment by nsanden** [comment]
Sorry, stand by... Seems the "danes" call isn't working now anymore. Perhaps something screwed up on my end.

**Comment by nsanden** [comment]
and.... now "danes" is working again. And now "great+danes" is working! Seems to be intermittent. I guess this is probably an internal Facebook issue not SDK issue.
