### ISSUE TITLE
[Access Token] Extend specific API version

### ISSUE THREAD

**Issue by MaksBrainiac** [facebook/facebook-php-sdk-v4#376]
public function extend($appId = null, $appSecret = null)
    return static::requestAccessToken($params, $appId, $appSecret);

Makes "GET https://graph.facebook.com/v2.0/oauth/access_token....." request,
can not set API version to 2.2.

**Comment by gfosco** [comment]
Are you using 4.0.20?  I'm looking at the code, and it should use the version specified in FacebookRequest, which is 2.2... there's no code there to specify 2.0.

**Comment by MaksBrainiac** [comment]
OK, new FacebookRequest default API version is 2.2,
How can I extend token using new Facebook Graph API Version 2.3?

**Comment by SammyK** [comment]
@MaksBrainiac Unfortunately there isn't a way to specify a Graph version number in 4.0 for extending an access token. It will just fallback to the default as specified in the SDK. You're using an old version of the PHP SDK that defaulted back to Graph v2.0. You'll need to upgrade your version of the PHP SDK to the latest Graph version for now.

I just submitted a PR #387 which bumps the Graph version to v2.3, so once that gets merged & tagged you can just upgrade to the latest 4.0 SDK version to default to Graph v2.3.
