### ISSUE TITLE
Facebook\Facebook -> delete() should have a "params" parameter

### ISSUE THREAD

**Issue by txptr** [facebook/facebook-php-sdk-v4#379]
Hey everybody,

recently I wondered, why the delete method in the Facebook-Class doesn't have a "params" parameter? For some Facebook Delete-Requests you need the params field to send 
additional data (e.g. unblocking a user - https://developers.facebook.com/docs/graph-api/reference/v2.2/page/blocked).

What do you think?

Greetings

**Comment by SammyK** [comment]
You are correct! It's seems to be fairly uncommon for `DELETE` requests to have an entity body, but if the Graph API supports it, so should the SDK.

Do you want to submit a PR for this & update the docs? :)

**Comment by txptr** [comment]
I hope I did everything right so far?!

**Comment by gfosco** [comment]
Merged #380
