### ISSUE TITLE
Q: Is there a good tutorial on how to upgrade from v3 to v4?

### ISSUE THREAD

**Issue by rvarbanov** [facebook/facebook-php-sdk-v4#382]
I am looking for a good tutorial on how up upgrade from v3 to v4.

PS: I am using CakePHP for my site. The tutorial does not need to cover CakePHP setup, but I thought it might be good to let you know what my dev environment is.

**Comment by SammyK** [comment]
There isn't, but I'm working on that actually. :)

**Comment by rvarbanov** [comment]
@SammyK 
This is the error I get:
```
Error: Class 'Facebook\Facebook' not found	
File: /path/to/www.sitename.com/app/Controller/AppController.php	
Line: XXX
```
I have my FB PHP SDK in app/Lib/Facebook;
in the AppController I have:
```
App::import('Lib/Facebook', 'autoload');
.
.
.
    protected function createFacebookObject() {
        $facebook = new Facebook\Facebook([
            'app_id'  =>  FB_APP_ID,
            'app_secret' =>  FB_SECRET,
            //'default_graph_version' => 'v2.2',
            //'default_access_token' => '{access-token}', // optional
        ]);

        return $facebook;
    }
```

I am not sure how familiar with CakePHP you are but thought I could try :)

So, my question is why do I get that error and how to fix it.

**Comment by SammyK** [comment]
Instead of trying to require the autoloader with `App::import('Lib/Facebook', 'autoload');`, try just using `require`.

```php
require(__DIR__.'/Lib/Facebook/autoload.php');
```

**Comment by rvarbanov** [comment]
Thank you @SammyK, I fixed my issue by moving the Facebook SDK from Lib into Vendor.

That seem to fix the issue.

**Comment by SammyK** [comment]
Glad you figured it out! :)

I'm still writing the upgrade guide. Shouldn't be too long. :)

**Comment by rvarbanov** [comment]
Please keep me posted.

**Comment by SammyK** [comment]
Just posted an [upgrade guide from v3.x to v4.1](https://www.sammyk.me/upgrading-the-facebook-php-sdk-from-v3-x-to-v4-1). Hope that helps! :)

**Comment by rvarbanov** [comment]
Thank you, Sammy for the great article.

I noticed that in your older article https://www.sammyk.me/best-pra... you have an extra catch(Facebook\Exceptions\FacebookResponseException $e)

Is Facebook\Exceptions\FacebookResponseException going away?

Also, can you use getDecodedBody() on $facebook->get('/me/permissions')?

Eg: 
$facebookUserPermissions = $facebook->get('/me/permissions');
$facebookUserPermissions = $facebookUserPermissions->getDecodedBody();

**Comment by SammyK** [comment]
> Thank you, Sammy for the great article.

No problem! :)

> Is Facebook\Exceptions\FacebookResponseException going away?

No, it's still there but it's only thrown when the Graph API returns an error response. The `FacebookSDKException` is the base exception so most all exceptions the SDK will throw can be caught by catching `FacebookSDKException`. You really just need to catch `FacebookResponseException` if you need to specifically differentiate between Graph API error responses and any general errors that the SDK might produce.

> Also, can you use getDecodedBody() on $facebook->get('/me/permissions')?

Yes, `getDecodedBody()` is a method on the `FacebookResponse` entity and the `get()`, `post()` & `delete()` methods on the `Facebook` super service all return `FacebookResponse` entities.
