### ISSUE TITLE
FacebookCurl error posting a link with feed_targeting

### ISSUE THREAD

**Issue by ggiacomo** [facebook/facebook-php-sdk-v4#383]
Hi all,
when a try to post a link on a facebook page using the feed_targeting, is returned this error:

Array to string conversion .../HttpClients/FacebookCurl.php:68

In the parameters array, this is how I set the feed_targeting:
.....,
'link' => 'www.example.com',
'message' => 'User provided message',
 'feed_targeting' => array(
     'age_min'=>20,
      'age_max'=>30,
),
....

Of course, without the feed_targeting part, it works.
Any suggestion? Thank you in advance.
Giacomo

**Comment by SammyK** [comment]
What version of the SDK are you using? 4.0 or 4.1?

**Comment by ggiacomo** [comment]
Hi, 
thanks for your reply. Using the last one, 4.0.20. Which one should I use?

**Comment by SammyK** [comment]
Just submitted PR #386 that should hopefully fix this for you. :)

**Comment by gfosco** [comment]
I'll tag a new release in a bit... feel free to re-open if you still have an issue.
