### ISSUE TITLE
Why can't I pass params to a GET request using the Facebook\Facebook object?

### ISSUE THREAD

**Issue by ruudk** [facebook/facebook-php-sdk-v4#384]
I want to specify `fields=id` and `metadata=1` using an params array... but it seems like the only way is to add it to the url instead?

**Comment by SammyK** [comment]
Sounds like you're in the same camp as #307 for adding an array of params argument to the `get()` method signature. I used to be +0 on that, but considering it seems to be a popular want and it's needed for the `delete()` method as well (#380), I wouldn't mind adding an array of `$params` as an arguments to `get()` and `delete()` in 4.2.

What do you think @yguedidi & @gfosco? :)

But to answer your question, @ruudk, the current API in 4.1 does not allow an array of params on `get()` so you'd have to pass them into the URL yourself.

**Comment by yguedidi** [comment]
+0 too :)

**Comment by yguedidi** [comment]
@ruudk or use `sendRequest()` directly ;)

**Comment by gfosco** [comment]
I'm also +0... I'd consider it if a PR is submitted for 4.2, but otherwise lets just use the URL.
