### ISSUE TITLE
Please fix getSessionFromRedirect()

### ISSUE THREAD

**Issue by clbphanmem** [facebook/facebook-php-sdk-v4#391]
We're using previous version of facebook api normally. But when i download the newest Version and run it on old source.It has error : 

"Fatal error: Cannot use object of type stdClass as array in C:\xampp\htdocs\fb2\Facebook\FacebookRedirectLoginHelper.php on line 191" 

Because FacebookRedirectLoginHelper on line 191 uses array and response is Object. I must convert Response into array and it run normally. Please fix or announce something about this issue. :(

Thanks.

**Comment by xmrflipflop** [comment]
Using 4.0.22, experiencing same things, what was the last working version? 
Suggest fix for line 191-193:
      if (isset($response->access_token)) {
        return new FacebookSession($response->access_token);
      }

**Comment by clbphanmem** [comment]
Thank you for responding so quickly. :+1: 
I have another way to fix it. I converted $respond to array, but i like your suggestion because it optimizer than my idea.

**Comment by SammyK** [comment]
Just submitted a fix for this: #393
