### ISSUE TITLE
4.0.22,  Fatal error: Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by yiliaofan** [facebook/facebook-php-sdk-v4#392]
Fatal error: Cannot use object of type stdClass as array in /xxxx/third_party/Facebook/FacebookRedirectLoginHelper.php on line 191

solve the problem:
      if ($response instanceof \stdClass && isset($response->access_token)) {
          return new FacebookSession($response->access_token);
      }
      if (is_array($response) && isset($response['access_token'])) {
        return new FacebookSession($response['access_token']);
      }

**Comment by SammyK** [comment]
Just submitted a fix for this: #393
