### ISSUE TITLE
When will 4.1 be available?

### ISSUE THREAD

**Issue by roman02** [facebook/facebook-php-sdk-v4#394]
I've been waiting for this version of the SDK before modifying my website's code (uses 3.x) to use the new version of FB Graph API. It's getting close to the middle of April, and Facebook has promised to stop supporting v.1 on April 30. Is there a high-certainty ETA for 4.1?

**Comment by SammyK** [comment]
@gfosco would have a better idea of the exact date of an official release, but you can upgrade your app now, [all the documentation is updated in GitHub](https://github.com/facebook/facebook-php-sdk-v4/tree/master/docs) and I wrote an [upgrade guide from v3 to v4.1](https://www.sammyk.me/upgrading-the-facebook-php-sdk-from-v3-x-to-v4-1) that might help you. :)

**Comment by ajessu** [comment]
> but you can upgrade your app now

+1.

I've been doing migrations with the 4.1 SDK of a major codebase for a while, and haven't had any major issues. In fact, I started with the current stable 4.0, and having seen the 4.1 improvements, I upgraded half way in through the migration, to take advantage of the many improvements it comes with, like listed results coming in a [`GraphList`](https://github.com/facebook/facebook-php-sdk-v4/blob/master/docs/GraphList.fbmd) among many many others goodies.

Also, as @SammyK pointed himself, that's an excellent guide to migrate apps from the old sdk.
I'd also recommend to watch some of his [excellent videos](https://www.sammyk.me/speaking)

Thanks @SammyK and the rest of the contributors. Looking forward to see 4.1 officially out soon!

**Comment by SammyK** [comment]
Aw, shucks. Thanks @ajessu! :)

**Comment by roman02** [comment]
Are you implying that 4.1 is already there, but hasn't been *officially* released? In other words, downloading from the master branch will yield 4.1?

**Comment by SammyK** [comment]
@roman02 Correct. :)

**Comment by roman02** [comment]
Will trust you. You seem trustworthy :)

**Comment by roman02** [comment]
@SammyK Do you have a video with your speech on "An entertaining intro to Graph Theory, the Facebook Platform and the new, NEW PHP SDK"? There are only slides on https://speakerdeck.com/sammyk

**Comment by SammyK** [comment]
> Will trust you. You seem trustworthy :)

Thanks! :)

> Do you have a video with your speech on "An entertaining intro to Graph Theory, the Facebook Platform and the new, NEW PHP SDK"?

Unfortunately not, but there is a [Laravel-flavored one](https://www.sammyk.me/speaking#laravel-chi-2015) that is the same talk until about 27 mins in. :)

**Comment by roman02** [comment]
Will 4.1 ever be released? It's April 28, 2015 already.

**Comment by gfosco** [comment]
You can use it by now switching to the master branch.  Unfortunately I haven't been able to get the new documentation loaded to the Facebook Developers site, which at the moment is a requirement before fully releasing 4.1.  I will try to get that done soon.
