### ISSUE TITLE
notifications with @[] in template throws couldn't open file error

### ISSUE THREAD

**Issue by vprajapa** [facebook/facebook-php-sdk-v4#395]
```php
$template = "@[12345234] is waiting";
$response = (new \Facebook\FacebookRequest($session, 'POST', "/$userId/notifications", array(
			'template' => $template,
			'href' => '',
			'access_token' => APP_ID."|".APP_SECRET
		)))->execute()->getGraphObject();

```
Fatal error: Uncaught exception 'Facebook\FacebookSDKException' with message 'couldn't open file "[12345234] is waiting"' in \vendor\facebook\php-sdk-v4\src\Facebook\HttpClients\FacebookCurlHttpClient.php on line 150

This works in graph api explorer. Also if I remove @[12345234] it works in php sdk.

**Comment by devsdmf** [comment]
Can you post the CURL error code ? I think that is a codification problem in the curly brackets of your template item in the parameters array, try to use the function url_encode in the template item.

**Comment by vprajapa** [comment]
that worked thank you!

**Comment by vprajapa** [comment]
request went through but the notification the user is getting looks something like this if I use urlencode.
%40%5B12345234%5D+is+waiting

Here is the curl error message I get if I do not use urlencode

curlErrorMessage: couldn't open file "[12345234] is waiting"
curlErrorCode: 26

**Comment by gfosco** [comment]
Seems like CURL is thinking this is a file reference, since that is how file paths are passed... Can you just start the notification with a different character?
