### ISSUE TITLE
Correctly versioning releases with semvar

### ISSUE THREAD

**Issue by pugsley** [facebook/facebook-php-sdk-v4#399]
We've just had a bunch of production failures because this package was upgraded from `4.0.20` > `4.0.23`. If you're following semver (http://semver.org/) then that's a patch version to patch version. Patch versions are intended for backwards-compatible bug fixes.

However amongst these patch versions the Facebook Graph endpoint was changed from version `2.2` > `2.3`, a massively significant change (https://github.com/facebook/facebook-php-sdk-v4/commit/085ed437a51720fe572402717d9e41e2204bc333).

IMHO when you bump the Facebook API version you should at least bump the minor version.
e.g. `4.0.20` > `4.1.0`.

**Comment by pugsley** [comment]
I should mention that this is probably a bit of a grey area because the changes made to this package WERE backwards compatible but the flow on effects of switching to `2.2` > `2.3` broke stuff.

**Comment by gfosco** [comment]
I wasn't aware going from 2.2 to 2.3 would be considered a BC.. In the future, will take this into account.

Unfortunately, this repo does not follow semver.  It was a mistake made when launched.  We do have 4.1 in the works, but it's a very large refactoring (see the master branch).. 

Thanks.

**Comment by yguedidi** [comment]
A solution to this would be to use unversionned graph calls
