### ISSUE TITLE
Get an access token server side

### ISSUE THREAD

**Issue by yamsellem** [facebook/facebook-php-sdk-v4#400]
It may sound trivial, but where / how are we supposed to get an access_token?
The doc says "Use one of the helper classes to get a FacebookSession object [...] or create a FacebookSession with a valid access token:" but do not say how.

Is it possible to get one from server-to-server?

ps. [this page](https://developers.facebook.com/docs/facebook-login/access-tokens#apptokens) explains how to generate tokens, but it seems that a web interface is always needed to do so

**Comment by unitoneict** [comment]
The docs make an overview about the classes that must be used, but did not offer a starter app that can help you start developing quickly. 

There is several tutorials and projects that offer that, you can check our starter app for example here:
https://github.com/FacebookArabia/starter-php-v4

If you need any other help do not hesitate to open new issue in our starter project

**Comment by gfosco** [comment]
It requires a call to the Graph API, not necessarily a web interface... at least for an "App Token".

**Comment by yamsellem** [comment]
This steps are working.

* Get a short-lived token (_with the `manage_pages` permission_) though the [Graph API Explorer](https://developers.facebook.com/tools/explorer)
* Convert this short-lived access token into a long-lived one though https://graph.facebook.com/oauth/access_token?client_id=&client_secret=&grant_type=fb_exchange_token&fb_exchange_token=
* Convert this long-lived access token in a permanent one (Expires: Never) though https://graph.facebook.com/me/accounts?access_token=

**Comment by yamsellem** [comment]
The two first steps (short-lived token obtained and converted in a long-lived) seem enough to get a never expiring token since api 2.4.
