### ISSUE TITLE
Fatal error: Class 'Facebook\FacebookSession' not found 

### ISSUE THREAD

**Issue by panigrc** [facebook/facebook-php-sdk-v4#402]
I am getting this error with the latest dev version, using composer to install the sdk ("facebook/php-sdk-v4": "4.1.*@dev") and having the following lines in my code (not in function or class) 

use Facebook\FacebookSession;
use Facebook\FacebookRequest;
use Facebook\GraphUser;
use Facebook\FacebookRequestException;
FacebookSession::setDefaultApplication('', '');

when using the stable version everything is fine, just letting you know.

**Comment by ferhtgoldaraz** [comment]
Do you have this line above them?:

    require 'vendor/autoload.php';

The php script that gets executed is the one against relative paths will be resolved, even in included or required files; so, if you're autoloading eveything installed through composer (and you are supposed to),
and it still doesn't work, try somehting like `var_dump(is_dir('vendor'));` to see if there are any path related issues you need to fix.

**Comment by yguedidi** [comment]
@panigrc 4.1 is a big refactoring but your code use 4.0. The SDK don't follow semver.
Check the README of the 4.1 branch to make it work, or require 4.0
