### ISSUE TITLE
[Insight] Files should not be executable

### ISSUE THREAD

**Issue by Tjoosten** [facebook/facebook-php-sdk-v4#403]
> Your project contains files with permissive permissions. In order to avoid opening a security breach, you should restrict execution rights on following files: 
- .travis.yml
- src/Facebook/FacebookBatchRequest.php
- src/Facebook/FacebookBatchResponse.php
- src/Facebook/FacebookRequest.php
- src/Facebook/FacebookResponse.php
- src/Facebook/FileUpload/FacebookFile.php
- src/Facebook/FileUpload/FacebookVideo.php
- src/Facebook/Http/GraphRawResponse.php
- src/Facebook/Http/RequestBodyInterface.php
- src/Facebook/PseudoRandomString/PseudoRandomStringGeneratorInterface.php
- src/Facebook/Url/FacebookUrlDetectionHandler.php
- src/Facebook/Url/FacebookUrlManipulator.php
- src/Facebook/Url/UrlDetectionInterface.php

```bash
chmod a-x '.travis.yml' \
    'src/Facebook/FacebookBatchRequest.php' \
    'src/Facebook/FacebookBatchResponse.php' \
    'src/Facebook/FacebookRequest.php' \
    'src/Facebook/FacebookResponse.php' \
    'src/Facebook/FileUpload/FacebookFile.php' \
    'src/Facebook/FileUpload/FacebookVideo.php' \
    'src/Facebook/Http/GraphRawResponse.php' \
    'src/Facebook/Http/RequestBodyInterface.php' \
    'src/Facebook/PseudoRandomString/PseudoRandomStringGeneratorInterface.php' \
    'src/Facebook/Url/FacebookUrlDetectionHandler.php' \
    'src/Facebook/Url/FacebookUrlManipulator.php' \
    'src/Facebook/Url/UrlDetectionInterface.php'
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/10eab2fc-8cef-4805-b677-686aaebdd6ae/analyses/1)_

**Comment by SammyK** [comment]
Easy enough. #409 should fix. Thanks for making it all cut & pasty. :)
