### ISSUE TITLE
Open Graph Support

### ISSUE THREAD

**Issue by devmsh** [facebook/facebook-php-sdk-v4#406]
I think that Open Graph is one of the greatest protocol that still not supported in the SDK. such a support may help on:

1. Having special Entity class for each built-in object type
1. Function to generate the meta tags
1. Function for each built-in supported action type
1. Helper function for updating, and deletion .. etc

It will be easier to use by websites, apps, and games developers?

**Comment by SammyK** [comment]
Sounds good! Can you elaborate a bit more on each point? I think there are multiple PR's here that could be discussed in their own issues. :)

**Comment by yguedidi** [comment]
I had this idea one day, but I don't spec it yet. So :+1:

**Comment by devmsh** [comment]
What I'm thinking about is to create a new Namespace `Facebook\GraphNodes\OpenGraphNodes`, and basic `OpenGraphObject` that inherited from the default `GraphObject`. the new subclass will contain the getters for each OG general fields like `description`, `image`, `title`, and `type`.

Then, for each built-in types we will have special class like `OpenGraphArticle` and this subclass will have the getters for each specific Article fields like `author`, `section` and `tag`.

Then we will allow the developer to cast the response to `OpenGraphObject` or `OpenGraphList` or `OpenGraph{type}` as we did for the current classes.

I think that the other parts of the idea must be discussed separability, because it effect both the current `GraphObject` and the new suggested `OpenGraphObject` as well. I suggest to develop the `GraphNodes` to have ORM like functionality and allow the user to delete or update some nodes directly using setter functions and `save` function that auto generate the required request. the same for `delete`. More advanced option is to have a relation function like `getLikes` or `addLike` and to offer eager or lazy-loading approach to get the data?

If the Idea is accepted in the `GraphObject` level, it will be used also in the new `OpenGraphObject` level to provide create new Actions like having `read` function in the `GraphObjectArticle` class and `scrape` or `update` function in the `OpenGraphObject` itself.

**Comment by SammyK** [comment]
We probably need to step back and disambiguate two very different concepts with similar names.

1. The [Open Graph Protocol](http://ogp.me/) is a widely adopted standard for defining a node within a social context. It's Facebook created, but not exclusive to Facebook.
2. Facebook has [Open Graph stories](https://developers.facebook.com/docs/sharing/opengraph) to control the details of how people interact with your app within Facebook specifically.

> What I'm thinking about is to create a new Namespace Facebook\GraphNodes\OpenGraphNodes, and basic OpenGraphObject that inherited from the default GraphObject. the new subclass will contain the getters for each OG general fields like description, image, title, and type.

If you're talking about the Open Graph Protocol, then this would need to go under it's own namespace (e.g. `Facebook\OpenGraphProtocol`) and not extend from `GraphObject` as it has nothing explicitly tying it to Graph nodes.

> Then, for each built-in types we will have special class like OpenGraphArticle and this subclass will have the getters for each specific Article fields like author, section and tag.

Are you referring to the [Open Graph Protocol types](http://ogp.me/#types) or Facebook's [default Open Graph object types](https://developers.facebook.com/docs/reference/opengraph#object-type)?

> Then we will allow the developer to cast the response to OpenGraphObject or OpenGraphList or OpenGraph{type} as we did for the current classes.

Can you explain in more detail why a developer might want to convert a Graph response directly into an Open Graph type? And can you also specify to which Open Graph you're referring? :)

Depending on where this conversation goes, I've had on my TODO list a feature to add a helper to deal with the Facebook scrapper to make dealing with OG tags easier... but I'll save that for a little bit later.

Again - thanks for the new and interesting ideas! Keep them coming! :)

**Comment by devmsh** [comment]
I'am talking about Open Graph Stories. But, While it build based on the Open Graph Protocol, the Protocol Object Types are subset of the Stories Object Types, which mean that we support both of them. Open Graph Protocol itself have many PHP library to generate, parse and validate, what we need is a support for the Open Graph Stories.

> If you're talking about the Open Graph Protocol, then this would need to go under it's own namespace (e.g. Facebook\OpenGraphProtocol) and not extend from GraphObject as it has nothing explicitly tying it to Graph nodes.

While Graph API return these stories in the same structure as standard Nodes and Edges, I think that extending the `GraphObject` and `GraphList` will be better? 

> Can you explain in more detail why a developer might want to convert a Graph response directly into an Open Graph type? And can you also specify to which Open Graph you're referring? :)

for the same reason he/she might want to convert a Graph response into a standard object type like GraphEvent. for example, A music app developer need to get the list of songs that a user listen to before, It will be better to have a `OpenGraphSong` with `getDuration` and auto mapped `musician` to `OpenGraphMusican` ... etc.

> Depending on where this conversation goes, I've had on my TODO list a feature to add a helper to deal with the Facebook scrapper to make dealing with OG tags easier... but I'll save that for a little bit later.

I think that re-scraping and meta generation is the most important functions to have in a the new `OpenGraphObject` or in a separated helper class. In the other hand, support for Custom Open Graph Stories must be taken into consideration.

> Again - thanks for the new and interesting ideas! Keep them coming! :)

I will stop talking about new ideas and contribute to deliver the accepted ones :P

Many thanks

**Comment by SammyK** [comment]
Cool. I'd be cool with having Open Graph subtypes that extend from `GraphObject`.

I'd say the `FacebookResponse` class could have getter methods for `getOpenGraph*()` and the subtypes would be prefixed with `OpenGraph*`.

Off the top my head I can't think of implementation details, but the broad scope sounds legit. :)

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by gfosco** [comment]
Our bot is a little aggressive.  I like leaving things open...

**Comment by gfosco** [comment]
Closing for now, you're free to submit again.
