### ISSUE TITLE
FacebookAuthorizationException: (#324) Requires upload file

### ISSUE THREAD

**Issue by ggiacomo** [facebook/facebook-php-sdk-v4#412]
Hi,
when I try to upload an image to a fb page ('PAGE_ID/photos'), with the 'url' parameter and an online image, works fine, but when I try with the 'source' parameter and a CurlFile, i get:
FacebookAuthorizationException: (#324) Requires upload file

$_photo = new CurlFile('/www/docs/WEBSITE/FOLDER/image.jpeg', 'image/jpeg');
$data = [
    'source' => $_photo,
    'access_token'   => 'PAGE_ACCESS_TOKEN',
];

The PAGE_ACCESS_TOKEN has these scopes:
user_friends, email, read_insights, manage_pages, publish_pages, publish_actions, public_profile

Any idea? Thank you in advance.

**Comment by ggiacomo** [comment]
Nevermind, solved :)

**Comment by pegasx** [comment]
How did you solve the problem? Please can you eplain it? Thanks.

**Comment by zikospeed** [comment]
On PHP 5.4 using 'source' => '@/path/to/file.name' always return  (#324) Requires upload file and i don't find any option to actividade file upload like exists in old version of SDK
