### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Alkasih** [facebook/facebook-php-sdk-v4#413]
I am using this script but when I tried to login it shows me: 

App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

I don't have an idea what I need to solve here. Please help.

**Comment by gfosco** [comment]
The app you have set up on the Facebook Developers site needs to be switched out of sandbox mode for normal users to access the app:  https://developers.facebook.com/docs/apps/security
