### ISSUE TITLE
GraphVideo support

### ISSUE THREAD

**Issue by devmsh** [facebook/facebook-php-sdk-v4#415]
While we are close to finish the support of `GraphEvent` (#405), I prepare my PR to support `GraphVideo` too.

Based on the docs: https://developers.facebook.com/docs/graph-api/reference/video, Video has `format` fields that return a `list<VideoFormat>`.

mmm I'm confusing why format is not an edge, but anyway! Is the SDK already have standard way to deal with fields that return a list of specific `Graph{Type}` objects?

The current implementation of `GraphObjectFactory` cast the `format` field to `GraphVideoFormat` that contain an array of `GraphObject` objects, but what we need is to have a `Collection` of `GraphVideoFormat` objects.

**Comment by SammyK** [comment]
Interesting... this one might be a little tricky. Can we put a hold on this one for now until we [get 5.0 tagged](https://github.com/facebook/facebook-php-sdk-v4/issues/411)?

If you're itching to contribute some more Graph node subtypes, do you want to tackle the `GraphGroup` next since that one is [referenced as an existing `@todo`](https://github.com/facebook/facebook-php-sdk-v4/pull/405/files#diff-2f4470c0bdf8a4acaccfb997e188e167R40)?

**Comment by devmsh** [comment]
I will push the group support PR once the event PR accepted so I can modify the event map array

For the Video did you mean to delay it at all, or to push ghe PR with Todo for the Format field support?

**Comment by SammyK** [comment]
> I will push the group support PR once the event PR accepted so I can modify the event map array

Perfect.

> did you mean to delay it at all, or to push ghe PR with Todo for the Format field support?

If you can come up with a great solution to tackle the issues you brought up, then feel free to send a PR. I was just saying that once we get past renaming 4.1 to 5.0, then we should have more eyeballs on your PR and proposed solution. And since `GraphGroup` is fairly low-hanging fruit, it'd probably get merged faster. :)

**Comment by devmsh** [comment]
@SammyK, when I refactor the `GraphUser` class, I detect that the `GraphVideoFormat` appear again many times. In the `GraphUser` we have:

1. `list<userdevice>`
1. `list<educationexperience>`
1. `list<experience>`
1. `list<string>`
1. `list<messagingsuggestedgroup>`
1. `list<workexperience>`
1. `agerange`
1. `usercontext`
1. `currency`
1. `paymentpricepoints`
1. `securitysettings`
1. `videouploadlimits`

All of these fields return `List`s of primitive type like `interested_in` which eturn `list<string>` or `List of `GraphNode` sub classes like `work` which return `list<GraphWorkExperience>`.

To support these type of fields, we must replace these lines in the `GraphNodeFactory` `safelyMakeGraphNode` function:

```php
// Could be a GraphEdge or GraphNode
$items[$k] = $this->castAsGraphNodeOrGraphEdge($v, $objectSubClass, $k, $parentNodeId);
```

to be
```php
if (is_assoc($v)) {
    // Could be a GraphEdge or GraphNode
    $items[$k] = $this->castAsGraphNodeOrGraphEdge($v, $objectSubClass, $k, $parentNodeId);
}else{
    // if not assoc array, it must be a GraphNode that contain a List
    $collection_items = [];
    foreach($v as $cv){
        $collection_items []= $this->castAsGraphNodeOrGraphEdge($cv, $objectSubClass, $k, $parentNodeId);
    }
    $items[$k] = new collection($collection_items);
}
```

`is_assoc($v)` check if the array is an associative array, it will continue as before, if not, this mean that this is a field return a list not a single value/object.

the `GraphEdge` data return in non-associative array, and it will still working because it will be handled from `castAsGraphNodeOrGraphEdge` function.

Did I missed any scenario?

**Comment by SammyK** [comment]
This is really great stuff @devmsh! Let's [figure out what to call these union type thingies](https://github.com/facebook/facebook-php-sdk-v4/issues/401#issuecomment-103241809) and then figure out the implementation details. :)

**Comment by devmsh** [comment]
:+1:

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by gfosco** [comment]
Our bot is a little aggressive.  I like leaving things open...

**Comment by gfosco** [comment]
Well.. I will close it for now.  You can submit again whenever.
