### ISSUE TITLE
getResult

### ISSUE THREAD

**Issue by rahulraj123456** [facebook/facebook-php-sdk-v4#416]
hai i want to know a php sdk v5 getResult fuction
please help me
It's urgent

**Comment by rahulraj123456** [comment]
please solve this solution:

get result in v4.0.0:
try {
  $page->api('/me/feed','POST',
                   array( 
                     'message' => 'Hello World!',
                     'link' => 'www.example.com'
                        )
                );
} catch(Exception $e) {
  $result = $e->getResult();
  error_log(json_encode($result));
}

like this i want for latest version in php sdk

**Comment by gfosco** [comment]
The docs are not loaded for the newest version, but you can see the source here for an example using the latest version (master branch):  https://github.com/facebook/facebook-php-sdk-v4/blob/master/docs/example_post_links.fbmd
