### ISSUE TITLE
GitHub pages for docs

### ISSUE THREAD

**Issue by SammyK** [facebook/facebook-php-sdk-v4#419]
Hey @gfosco - if you're pretty sure the "docs in GitHub pages" will get approved, can you create a project GitHub page so I can start porting over the docs it? :)

**Comment by yguedidi** [comment]
@SammyK look to [couscous.io](http://couscous.io/) :)

**Comment by SammyK** [comment]
Holy crap! :+1: for Couscous!

**Comment by SammyK** [comment]
@yguedidi Does that mean if @gfosco just [creates a `gh-pages` orphan branch](https://help.github.com/articles/creating-project-pages-manually/#create-a-gh-pages-branch) we can start PR'ing to it with Couscous?

**Comment by gfosco** [comment]
Update on this.... we're going to continue using the Facebook developers site, and I've gotten some help fixing the issue I was having before.  Next week I will load these... Promise!

**Comment by SammyK** [comment]
> Next week I will load these... Promise!

Bam! Thanks buddy! :)
