### ISSUE TITLE
The requested package facebook/php-sdk-v4 ~4.1.0@dev could not be found.

### ISSUE THREAD

**Issue by marijang** [facebook/facebook-php-sdk-v4#426]
I get this error The requested package facebook/php-sdk-v4 ~4.1.0@dev could not be found.

**Comment by gfosco** [comment]
Was hoping that would still work.. We're going to make it 5.0 and start following semver.

https://packagist.org/packages/facebook/php-sdk-v4

**Comment by marijang** [comment]
I need 4.1 because:D

https://github.com/SammyK/LaravelFacebookSdk

TNX

**Comment by SammyK** [comment]
Hum.... the `~4.1.0@dev` should still work since we have a `4.1-dev` branch... @yguedidi Does @gfosco just need to tag 4.1 on that branch to get the old alias to start working again?

@marijang I'll update my LaravelFaceboookSdk package today so you won't have this issue. :)

**Comment by marijang** [comment]
You can put ~5./@dev?

**Comment by SammyK** [comment]
This issue [has been fixed](https://github.com/SammyK/LaravelFacebookSdk/issues/61) in LaravelFacebookSdk. :)
