### ISSUE TITLE
Simplifying usage

### ISSUE THREAD

**Issue by hassankhan** [facebook/facebook-php-sdk-v4#429]
Could `GraphObject` at least use the `__get()` magic method rather than forcing everyone to use `getProperty()` every time?

Doing it this way, all subclasses will automatically get the same (IMO useful) behaviour

**Comment by devmsh** [comment]
Please review this related discussion
https://github.com/facebook/facebook-php-sdk-v4/issues/401#issuecomment-94303886

**Comment by yguedidi** [comment]
[Magic is a pain](http://3v4l.org/PEdCD). /cc @SammyK :)

**Comment by SammyK** [comment]
I used to be in the magic camp, but I'm with @yguedidi now. :)

It might be useful to allow users to set a base `GraphNode` subtype so that they can add magic methods or whatever other things they thought would be helpful.

```php
namespace Foo;

class MyGraphNode extends Facebook\GraphNodes\GraphNode {}

$fb = new Facebook\Facebook([
    'base_graph_node' => 'Foo\MyGraphNode',
]);
```

Thoughts?

**Comment by hassankhan** [comment]
I would just like all properties retrieved from the Graph API to be accessible as public members of the `GraphObject` class. 

Instead of having to do `$graphObject->getProperty('link')`, I'd like to be able to do `$graphObject->link`.

**Comment by yguedidi** [comment]
@SammyK 
Personal opinion: I'm totally against this.
Why I'm against: it's overkill, why not add an option to make coffee? Should be a must have option lol :)
Why it's overkill: it's not in the scope of the SDK IMO, Graph returns object, SDK should too.

@hassankhan, if you really want to use magic, here a simple solution thanks to *composition*:
```php
class MyGraphObjectWrapper {
    private $graphObject;

    public function __construct(GraphObject $graphObject)
    {
        $this->graphObject = $graphObject;
    }

    public function __get($name)
    {
        return $this->graphObject->getProperty($name);
    }
}
```

**Comment by hassankhan** [comment]
From a consumer point-of-view, it's needlessly complex. I don't care enough to argue about it, but asking users (who are already struggling to learn how to use the SDK) to create their own object just to be able to get what are already essentially properties on the item. If magic methods are out of the question, what about making `GraphObject` extend `ArrayAccess` then?

**Comment by yguedidi** [comment]
Why not for `ArrayAccess`. :)

**Comment by hassankhan** [comment]
Is that a yes? Happy to do a PR if so

**Comment by yguedidi** [comment]
I still don't like the main idea.

For me, semantically, a `GraphObject` represent a Graph node, which is an entity with some properties, not "just" a collection of key indexed fields.
One more this, how to handle the set value part of array access? Throw an exception? NOP? Change the value in the `graphObject`? Too weird.

ping @gfosco @SammyK, your thoughts?

@hassankhan Why `getProperty()` is "needlessly complex"?

**Comment by hassankhan** [comment]
Semantically, you're completely in the right. Practically, as a user, I'd expect the properties of the entity to be available on the object.

I'm not sure I would even want to be able to set things (or if there even is a use-case), and I'm assuming (massive assumption here) that most people use it to receive data, not send. Could be wrong, in which case I'll shut up :smile:

**Comment by yguedidi** [comment]
Would a `getField()` alias of `getProperty` makes more sense for you?

About setting things, I mean when you implement `ArrayAccess` you must implement `offsetSet()`, so how to handle this case? Because Graph responses are immutable, and AFAIK it doesn't make sense to make them mutable.

@SammyK as you rename `GraphObject` to `GraphNode`, it may be useful to deprecate `getProperty()` in favor of `getField()` no?

**Comment by hassankhan** [comment]
That's literally just renaming the method, my point is I would rather avoid a function call to look up a property. If you _do_ implement `ArrayAccess`, then just throw an `Exception` or something in the `offsetSet()` method, saying not allowed or something. 

In an ideal world, I'd like to do this:

```php
$object = $request->execute->getGraphObject();

echo $object->link;
$object->description = 'New description';
$object->save();
```

**Comment by SammyK** [comment]
> as you rename GraphObject to GraphNode, it may be useful to deprecate getProperty() in favor of getField() no?

Really good point! I'm down! I can add that to the existing PR really quickly before @gfosco merges. Lol. :)

> If you do implement `ArrayAccess`,

All `GraphObect`'s extend from `Collection` which implement `ArrayAccess`. So you can do this instead of using `getProperty()`:

```php
$name = $graphObject['name'];
```

> In an ideal world, I'd like to do this [...] `$object->save();`

Node entities obtained from Graph responses are [immutable](http://en.wikipedia.org/wiki/Immutable_object) by design. What you're proposing is something like an ORM which [has been proposed before](https://github.com/facebook/facebook-php-sdk-v4/issues/407) but doesn't really fit into the SDK support model. It'd make an excellent open source project though! :)

**Comment by hassankhan** [comment]
Thanks for taking the time to reply. In the latest 4.x release (not master) it does, when will it actually be released?

**Comment by SammyK** [comment]
> In the latest 4.x release GraphObject doesn't extend Collection

Ah, yes. Forgot that `Collection` was added to just v5. I'm :+1: for a PR adding `ArrayAccess` to `GraphObject` in 4.0 if @yguedidi and @gfosco are down. :)

**Comment by gfosco** [comment]
Yeah, I have no problem with that.

**Comment by hassankhan** [comment]
Awesome, thanks guys!

**Comment by yguedidi** [comment]
:+1:
