### ISSUE TITLE
GraphObject doesn't return a posts' type

### ISSUE THREAD

**Issue by hassankhan** [facebook/facebook-php-sdk-v4#430]

**Comment by SammyK** [comment]
Can you give some more details?

**Comment by hassankhan** [comment]
Relevant code:

```
$session = new FacebookSession( env( 'FACEBOOK_ACCESS_TOKEN' ) );
$request = new \Facebook\FacebookRequest( $session, 'GET', '/' . $this->extractPostIdFromUrl() );
$response = $request->execute()->getGraphObject();
$response->getProperty( 'type' ); // Doesn't work
```

Basically I just wanted to see what type a post was, according to the SDK I should have:

Name | Description | Type
--- | --- | ---
type | A string indicating the object type of this post. | `enum{link, status, photo, video, offer}`

**Comment by hassankhan** [comment]
So I found adding `metadata=true` to the end of the URL gives me that extra information in _yet_ another `GraphObject`. Is there any way to force the SDK to automatically retrieve metadata?

**Comment by SammyK** [comment]
I don't know what `$this->extractPostIdFromUrl()` is doing in your code, but it's probably limiting the fields you're getting back & `type` is not in that. Make sure you use the `fields` param to specify what fields you would like returned.

For example if you just wanted the post `id` & `type` you'd do this:

    GET /{post-id}?fields=id,type

**Comment by hassankhan** [comment]
Basically the idea is I get the URL of a Facebook post and sometimes it looks like `/posts/{id}`, sometimes it's `/v.{numbers}/{id}` and for audio it's something else. That `extract` method grabs just the ID, I wasn't sure of a better way of doing that.

I just thought it would return all the information specified in the docs, didn't know you could specify fields you wanted. Thanks!!
