### ISSUE TITLE
`require __DIR__` in README.md causes misunderstanding

### ISSUE THREAD

**Issue by unarist** [facebook/facebook-php-sdk-v4#433]
```php
// Skip these two lines if you're using Composer
define('FACEBOOK_SDK_V4_SRC_DIR', '/path/to/facebook-php-sdk-v4/src/Facebook/');
require __DIR__ . '/path/to/facebook-php-sdk-v4/autoload.php';
```

Is `/path/to/facebook-php-sdk-v4/` absolute path or relative path?

I think `__DIR__` should be used in both or none of `define` and `require`.

There is same example in https://developers.facebook.com/docs/php/gettingstarted/4.0.0 .

**Comment by SammyK** [comment]
Good point. It's absolute but you can use a relative path if you like.

**Comment by unarist** [comment]
For example, if I wrote this code in `/home/hoge/someproject/index.php`...

```php
require __DIR__ . '/path/to/facebook-php-sdk-v4/autoload.php';
```

It loads `autoload.php` from `/home/hoge/someproject/path/to/facebook-php-sdk-v4/`, right?

**Comment by SammyK** [comment]
Correct

**Comment by unarist** [comment]
So following the example causes `Fatal error: Class ... not found` because `__DIR__` is only appended to including `autoload.php`.

Why don't you append `__DIR__` in both of `define` and `require`

```php
// Skip these two lines if you're using Composer
define('FACEBOOK_SDK_V4_SRC_DIR', __DIR__ . '/path/to/facebook-php-sdk-v4/src/Facebook/');
require __DIR__ . '/path/to/facebook-php-sdk-v4/autoload.php';
```

or none of those?

```php
// Skip these two lines if you're using Composer
define('FACEBOOK_SDK_V4_SRC_DIR', '/path/to/facebook-php-sdk-v4/src/Facebook/');
require '/path/to/facebook-php-sdk-v4/autoload.php';
```

**Comment by SammyK** [comment]
The `FACEBOOK_SDK_V4_SRC_DIR` constant is only necessary if you move the source files of the PHP SDK. Unless you moved the PHP files in the `src/Facebook` folder, you shouldn't need the define and you can just do:

```php
require __DIR__ . '/path/to/facebook-php-sdk-v4/autoload.php';
```

**Comment by unarist** [comment]
> The FACEBOOK_SDK_V4_SRC_DIR constant is only necessary if you move the source files of the PHP SDK.

I didn't know that until I read `autoload.php`. Is that explained in any document?

**Comment by SammyK** [comment]
> Is that explained in any document?

[It sure is](https://github.com/facebook/facebook-php-sdk-v4/blob/master/docs/sdk_getting_started.fbmd#L56-L104) (for v5).

> comment lines in the example mentioned about only using composer or not.

Yeah, it's a little confusing in the README in the 4.0 branch. But [the master (v5) branch README](https://github.com/facebook/facebook-php-sdk-v4/tree/master#usage) doesn't mention the autoloader. It probably should make a clear reference.

**Comment by unarist** [comment]
Oh, I didn't care about v5 branch. Looks nice!
