### ISSUE TITLE
[5.0][Proposal] Move and rename PersistentData and PseudoRandomStringGenerator

### ISSUE THREAD

**Issue by yguedidi** [facebook/facebook-php-sdk-v4#441]
Thoses namespace are dedicated to the state, so i suggest to:
- Rename `PersistentData` to `StateStorage`
- Rename `PseudoRandomStringGenerator` to `StateGenerator`
- Move them from root to a `State` namespace in `Authentication`

More Domain-specific :)

**Comment by SammyK** [comment]
I do like the DSL changes! One thing I want to consider before renaming `PersistentData`; would there be other cases where the SDK would need to store anything in persistent storage?

**Comment by yguedidi** [comment]
Humm I don't think

**Comment by SammyK** [comment]
Then I'm :+1:  :)

Although at this point any changes like this should be tagged 6.0 or just no tag at all. I don't want to hold off on getting the docs pushed to the dev site. :)

**Comment by gfosco** [comment]
There's time to get it in, honestly...

**Comment by yguedidi** [comment]
@gfosco The 5.0 release? or this proposal?

**Comment by SammyK** [comment]
> There's time to get it in, honestly...

![](http://media.giphy.com/media/bjfv14wZU7PiM/giphy.gif)

**Comment by gfosco** [comment]
I was saying you could get this proposal in, if it doesn't take too long..  but if you want to wait, then we'll launch without.

**Comment by gfosco** [comment]
So we didn't get this in, but you can open a PR for 6.0.

**Comment by yguedidi** [comment]
Will do after the 5.0 release :)
