### ISSUE TITLE
Where is index.php file or how to use this for testing

### ISSUE THREAD

**Issue by tushar4monto** [facebook/facebook-php-sdk-v4#444]
Hello
In test folder there is lots-off file which file i use ?

==> You defile Minimal example:in read me file but don't define where create this file and file name.

==> i also use composer  
3) The tests can be executed by running this command from the root directory:
means where i use this command i an using win7 what this command did??.
./vendor/bin/phpunit

This all are very confusing please provide one file for testing like index.php or etc

**Comment by SammyK** [comment]
Hey @tushar4monto!

> what this command did??.

The `./vendor/bin/phpunit` command executes automated [unit tests](http://en.wikipedia.org/wiki/Unit_testing) against the PHP SDK using [phpunit](https://phpunit.de/). There is no `index.php` entry point like you might expect in a typical web server setup.

If you're unfamiliar with running automated unit tests, check out [this unit testing intro](http://www.sitepoint.com/tutorial-introduction-to-unit-testing-in-php-with-phpunit/) by [Chris Cornutt](https://twitter.com/enygma).

If you're looking for more documentation or examples, check out the [latest documentation in the GitHub repo](https://github.com/facebook/facebook-php-sdk-v4/tree/master/docs).

> where i use this command i an using win7

Typically developers use a virtual server environment to run tests and run the web server for their projects. Check out this [intro to setting up a virtual environment on Windows](http://www.sitepoint.com/getting-started-vagrant-windows/).

Hope that helps!
