### ISSUE TITLE
FacebookRedirectLoginHelper returning NULL

### ISSUE THREAD

**Issue by netjordan** [facebook/facebook-php-sdk-v4#445]
Hello,

I am using the following code, however $helper->getSessionFromRedirect() always seems to return NULL.

```php
        $helper = new FacebookRedirectLoginHelper(
            'http://mydomain.com/facebook-return'
        );

        try {
            $fb_session = $helper->getSessionFromRedirect();
        } catch (FacebookRequestException $ex) {
            $fb_session = null;
            var_dump($ex);
        } catch (\Exception $ex) {
            $fb_session = null;
            var_dump($ex);
        }

        var_dump($fb_session);

        if ($fb_session) {
            $request = new FacebookRequest($fb_session, 'GET', '/me');
            $response = $request->execute();

            $graphObject = $response->getGraphObject();

            $fb['id'] = $graphObject->getProperty('id');
            $fb['name'] = $graphObject->getProperty('name');
            $fb['email'] = $graphObject->getProperty('email');

            print_r($fb);
        } else {
            echo 'Error';
        }
```

**Comment by angelxmoreno** [comment]
same issue. I noticed that FacebookRedirectLoginHelper::isValidRedirect() tries to compare the length of the saved state ( a random string created in  FacebookRedirectLoginHelper::getLoginUrl and saved to session) with that of $_GET['code']. I fail to see a situation when these are ever going to match.

**Comment by SammyK** [comment]
> tries to compare the length of the saved state [..] with that of $_GET['code']

Hum, it shouldn't be. Where in the code do you see that?

**Comment by facebook-github-bot-1** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by angelxmoreno** [comment]
@SammyK https://github.com/facebook/facebook-php-sdk-v4/blob/4.0.19/src/Facebook/FacebookRedirectLoginHelper.php#L206 shows the variable `$savedState` being set to the `code` get param rather than the stored value of the `state` parameter. Later on lines 211 - 213 the length of `$savedState` is compared to the provided state. These two will most likely never be the same. 

Looking at version 4.0.23 this has already been addressed https://github.com/facebook/facebook-php-sdk-v4/blob/4.0.23/src/Facebook/FacebookRedirectLoginHelper.php#L214

Please close this ticket.

**Comment by kimsal** [comment]
Sorry I still can't use it.

**Comment by angelxmoreno** [comment]
@kimsal if you require help then you need to make it easy to help you. Please provide more details on your situation. what version are you using? are you using composer? what version of PHP are you using? these are basic and very important questions you should be telling us if indeed you wish to get help.
