### ISSUE TITLE
Set Curl options dynamically

### ISSUE THREAD

**Issue by samward1985** [facebook/facebook-php-sdk-v4#446]
Currently, there doesn't seem to be a way to cleanly set Curl options (CURLOPT_CONNECTTIMEOUT, CURLOPT_TIMEOUT, etc.) when using FacebookRequest->execute(). As it is, FacebookCurlHttpClient->send() gets called, which opens the connection and sets a static set of Curl options. It'd be cool if, for example, we could set the HttpClientHandler and pass Curl options to it before executing the request, sort of how FacebookCurlHttpClient->addRequestHeader() works.

**Comment by SammyK** [comment]
In v4.0 of the SDK you can overwrite the HTTP client with your own handler using your own options. So you can have a custom cURL handler and inject it. I wrote a blog about [injecting custom HTTP clients into v4.0](https://www.sammyk.me/using-guzzle-4-http-client-with-facebook-php-sdk-v4) that might help.

**Comment by samward1985** [comment]
@SammyK Awesome! Looks really straightforward. Thanks!!
