### ISSUE TITLE
how to user this for login with facebook

### ISSUE THREAD

**Issue by tushar4monto** [facebook/facebook-php-sdk-v4#457]
Hello 
I user this sdk with install composer and i have now all package like vender etc

there is php syntax error in your code 
try {
  $me = (new FacebookRequest(
    $session, 'GET', '/me'
  ))->execute()->getGraphObject(GraphUser::className());
  echo $me->getName();
} catch (FacebookRequestException $e) {
  // The Graph API returned an error
} catch (\Exception $e) {
  // Some other error occurred
}

Please check and please give me one example.
I want login with facebook in may project but i dont know how to use this SDK please help me.

**Comment by gfosco** [comment]
Check the new documentation for 5.0 (Will be live tomorrow) which will have several new examples.  https://developers.facebook.com/docs/php

**Comment by SammyK** [comment]
> Will be live tomorrow

![](http://media.giphy.com/media/LrmvzKSwELME8/giphy.gif)
