### ISSUE TITLE
Upload Image : Error Cannot Open File

### ISSUE THREAD

**Issue by nratifainah** [facebook/facebook-php-sdk-v4#458]
I tried to post status with image to facebook. I had followed the instruction
 $response = (new FacebookRequest(
      $session, 'POST', '/me/photos', array(
        'source' => new CURLFile('path/to/file.name', 'image/png'),
        'message' => 'User provided message'
      )
    ))->execute()->getGraphObject();

 but I get error "couldn't open file".

How do I fix it? Thanks

**Comment by gfosco** [comment]
Sounds like the file path you're providing is not valid.  Please test accessing this without using the SDK.
