### ISSUE TITLE
getState returns NULL in validateCsrf

### ISSUE THREAD

**Issue by Nathorr** [facebook/facebook-php-sdk-v4#459]
SDK v4.4.1 (dev)

I'm trying to implement FB login to my school project. After hours of trying, it still returns 'Cross-site request forgery validation failed. Required param "state" missing.' exception.

For some reason variable $state is NULL even after getState(). getCode() works correctly, though. If I comment line 248 ($this->validateCsrf();) in FacebookRedirectLoginHelper.php, everything works fine, but then I'm vulnerable to csrf.

**Comment by gfosco** [comment]
Please try this with version 5.0.x and re-open if you're still having a problem.  Sorry for the late reply.
