### ISSUE TITLE
Class 'Facebook\FacebookSession' not found

### ISSUE THREAD

**Issue by MarcosPortugal** [facebook/facebook-php-sdk-v4#460]
I am using the facebook php sdk without composer, and my code was this:

```

define('FACEBOOK_SDK_V4_SRC_DIR', '/lib/facebook-php-sdk-v4-4.0-dev/src/Facebook/');
require __DIR__ . '/lib/facebook-php-sdk-v4-4.0-dev/autoload.php';

use Facebook\FacebookSession;
use Facebook\FacebookRedirectLoginHelper;

FacebookSession::setDefaultApplication('key', 'secret');

```

 And it was telling me the class FacebookSession could not be found, when it ran that last statement. By adding this line

```
require_once(FACEBOOK_SDK_V4_SRC_DIR . 'FacebookSession.php');
```

before the first "use", the error was gone. Something seems to be wrong here.

**Comment by SammyK** [comment]
You shouldn't need the `define()` line unless the autoloader is having trouble locating the source. So I'd try deleting that line and seeing if it works.

Otherwise, the line should be:

```php
define('FACEBOOK_SDK_V4_SRC_DIR', __DIR__ . '/lib/facebook-php-sdk-v4-4.0-dev/src/Facebook/');
```
