### ISSUE TITLE
Call to a member function api() on array 

### ISSUE THREAD

**Issue by fidel037** [facebook/facebook-php-sdk-v4#463]
Cant post to page. I got all needed params but when I try to execute       	$pages->api()->api( "/" . $pages['data'][0]['id'] . "/feed", 'post', $params );  i get 
Call to a member function api() on array

**Comment by gfosco** [comment]
What is the type of $pages?...

**Comment by fidel037** [comment]
Its an array of my fb pages...

**Comment by gfosco** [comment]
An array isn't going to have an api method...  5.0.0 is going to release today, so I'd suggest looking at the newest version and the documentation will be at developers.facebook.com/docs/php
