### ISSUE TITLE
GraphEdge or GraphNode

### ISSUE THREAD

**Issue by Pietro-Vis** [facebook/facebook-php-sdk-v4#469]
I upgraded the sdk today, and i'm facing an issue with the new distinction with graphEdge and graphNode.
How am i supposed to distinguish between the two programmatically? 
Is it possible to do in a predictable way or i need to use a try catch block every time?

**Comment by yguedidi** [comment]
You don't need to distinguish them programmatically, I guest you know what you request for? :)
If you request `/me`, it's a node, if you request `/me/feed`, it's an edge.

**Comment by Pietro-Vis** [comment]
Yes you are right, but i'm using a unique method to make requests to graph api, so it would be much easier if a method to detect edge or node in the response would be provided.
Anyway now i'm using this workaround: 

```php
$req = $this->client->{$opts}($url, $params);
$res = [];
try {
  $edge = $req->getGraphEdge();
  foreach ($edge as $node) {
    $res[] = $node->asArray();
  }
} catch (Exception $e) {
  $node = $req->getGraphNode();
  $res = $node->asArray();
}
```

**Comment by Pietro-Vis** [comment]
Nevermind, i found the method FacebookResponse->getDecodedBody which allows me to get the response as an array indipendently from the graph object type.
