### ISSUE TITLE
FacebookSession requires DefaultApplication because of enableAppSecretProof

### ISSUE THREAD

**Issue by datenbrille** [facebook/facebook-php-sdk-v4#472]
Hi,

thanks for this great library. I encountered a problem while using it without setting the DefaultApplication data.

I was doing this:
```php
$helper = new FacebookRedirectLoginHelper($this->getRedirectUri(),$this->getAppId(),$this->getAppSecret());
$session = $helper->getSessionFromRedirect();
```
and got the error message that the secret wasn't set.

This happens because of:
```php
public function getAppSecretProof($token)
{
    return hash_hmac('sha256', $token, FacebookSession::_getTargetAppSecret());
}
```
in FacebookRequest.php. The function is called in the constructor (Line: 207) and I didn't found a way to pass the app secret.

It is a requirement to use something like
```php
FacebookSession::setDefaultApplication('YOUR_APP_ID','YOUR_APP_SECRET');
```
somewhere in the code? I tried to avoid the global static call.

Thanks in advance.

I use version 4.0.23 of the library.

**Comment by SammyK** [comment]
> I tried to avoid the global static call.

Unfortunately version 4.0 relied on statics for things like this so you'll need the `FacebookSession::setDefaultApplication()` line to get it to work properly.

Have you checked out the [latest version of the SDK v5](https://developers.facebook.com/docs/reference/php/5.0.0) yet? I wrote a ["v4.0 to v5" upgrade guide](https://www.sammyk.me/upgrading-the-facebook-php-sdk-from-v4-to-v5) that might help. :)

**Comment by datenbrille** [comment]
Thanks, I will have a look and will put a ticket on my board.
