### ISSUE TITLE
Data response differs from Graph api explorer and SDK using App token

### ISSUE THREAD

**Issue by MrBrightside29** [facebook/facebook-php-sdk-v4#474]
If I make a batch request from my php script using my App token, the result differs from the Graph Api Explorer using the same App token. The Graph Api Explorer shows more and detailed information for some places in the response. I've checked several times that I'm using the same token in both places.

Here is my code:
````
$fb = new Facebook\Facebook([
            'app_id' => 'xxxxxxxxxxxxxxxxxxx',
            'app_secret' => 'yyyyyyyyyyyyyyyyyyyyyyyy',
            'default_graph_version' => 'v2.4',
            'default_access_token' => 'xxxxxxxxxxxxxxxxxxx|yyyyyyyyyyyyyyyyyyyyyyyy',
        ]);

        $batch = [
            $fb->request("GET", "search?distance=8000&center=40.0458951,0.0625485&q=pub&type=place&fields=location,name,description,hours,phone,price_range,category,category_list,cover,link&limit=100"),
        ];

        $responses = $fb->sendBatchRequest($batch);
````

Thanks for your help.

**Comment by SammyK** [comment]
Are you referring to the [debug info](https://developers.facebook.com/docs/graph-api/using-graph-api/v2.4#debugging)? Or what is the difference in response data that you are expecting?

**Comment by MrBrightside29** [comment]
No, it is not the debug info. Is the data of the places it returns. For example, the data of this place:

In the Graph Api Explorer shows:
````
{
  "data": [
    {
      "location": {
        "street": "Calle Bayer, 17.",
        "city": "Benicasim",
        "state": "",
        "country": "Spain",
        "zip": "12560",
        "latitude": 40.0546494,
        "longitude": 0.06435
      },
      "name": "Pub Magic",
      "hours": {
        "tue_1_open": "18:30",
        "tue_1_close": "03:00",
        "wed_1_open": "18:30",
        "wed_1_close": "03:00",
        "thu_1_open": "18:30",
        "thu_1_close": "03:00",
        "fri_1_open": "18:30",
        "fri_1_close": "03:00",
        "sat_1_open": "18:30",
        "sat_1_close": "03:00",
        "sun_1_open": "18:30",
        "sun_1_close": "03:00"
      },
      "price_range": "$ (0-10)",
      "category": "Bar",
      "category_list": [
        {
          "id": "110290705711626",
          "name": "Bar"
        }
      ],
      "cover": {
        "cover_id": "800830999990675",
        "source": "https://scontent.xx.fbcdn.net/hphotos-xaf1/v/t1.0-9/s720x720/10260026_800830999990675_9164363181881227279_n.jpg?oh=b780a555dbcfda94867f39788c229d0e&oe=565B5399",
        "offset_y": 50,
        "offset_x": 0
      },
      "link": "https://www.facebook.com/pages/Pub-Magic/102689216471527",
      "id": "102689216471527"
    }, 
......
````

And in my php, returns:

`````
"data": [
    {
      "location": {
        "street": "Calle Bayer, 17.",
        "city": "Benicasim",
        "state": "",
        "country": "Spain",
        "zip": "12560",
        "latitude": 40.054989674905,
        "longitude": 0.064181202760393
      },
      "name": "Magic Benicasim",
      "description": "Abierto viernes y sábado a las 22:30 hasta las 3:30",
      "category": "Local business",
      "category_list": [
        {
          "id": "2500",
          "name": "Local Business"
        }
      ],
      "link": "https://www.facebook.com/pages/Magic-Benicasim/158053270944613",
      "id": "158053270944613"
    },

`````
Can you see the difference? I think is something related to the token because it shows the same data as if you make the call with the default graph api explorer token.

**Comment by SammyK** [comment]
How are you handling the response object? Are you parsing it as a plain string, array or `GraphNode`? Is that the only request you're sending in the batch? If so, is there a reason you're sending it as a batch? Batch requests [return responses back a little differently](https://developers.facebook.com/docs/graph-api/making-multiple-requests) depending on what requests you're sending. I'd try sending it as a normal request to see if it matches what you get back from the Graph API explorer:

```php
$response = $fb->get('/search?distance=8000&center=40.0458951,0.0625485&q=pub&type=place&fields=location,name,description,hours,phone,price_range,category,category_list,cover,link&limit=100');
```

**Comment by MrBrightside29** [comment]
Right now I'm just doing a var_dump of the response to check the results but previously I was parsing it as a GraphNode. The code that I posted only has a single request in the batch but in my code it has around 15 requests.
The weird thing is that I've just tried to make the normal request you've posted and it returns the "expected" values, I mean, the same values as the Graph Api Explorer.

**Comment by SammyK** [comment]
> I've just tried to make the normal request you've posted and it returns the "expected" values, I mean, the same values as the Graph Api Explorer.

That's what I suspected. I'd double check the batch docs (linked in the previous post) to ensure there isn't any weird thing going on where the batch responses are being truncated for any reason.

If it's still not giving the expected values, I'd [submit a bug report](https://developers.facebook.com/bugs/trending/) since it might be a bug with batches.

**Comment by MrBrightside29** [comment]
Ok, thank you for your fast help. I appreciate it.

**Comment by SammyK** [comment]
Np :)

**Comment by gfosco** [comment]
@SammyK I owe you so many drinks. :+1:

**Comment by SammyK** [comment]
@gfosco And I owe you many as well. I think drinking is certainly in our future. :)

**Comment by MrBrightside29** [comment]
@SammyK any update on the batch problem?

**Comment by SammyK** [comment]
@MrBrightside29 Did you submit a bug report to the Graph API people?

**Comment by MrBrightside29** [comment]
@SammyK Sorry, my fault. I thought you'd going to submit the bug report.
