### ISSUE TITLE
https is not detected when $redirectUrl is not specified

### ISSUE THREAD

**Issue by moldcraft** [facebook/facebook-php-sdk-v4#476]
I am building a site for `.space` domain. I finished Facebook login on my localhost, where I use a local, not existing, `.dev` domain. On localhost the login app works well.

But when I placed my code live on `.space` domain, I get `Invalid redirect_uri` error after the user approved the app and was redirected back to my site, and in url I have `https://my-site.space/user/oauth/facebook?code=...` *(when the script tries to exchange the code for an access token)*.

* I have added `my-site.space` to **App Domains**
* I have added `https://my-site.space/` *(and all possible combinations, full url, with and without `https`)* to **Valid OAuth redirect URIs** 
* I have set **Client OAuth Login, Embedded Browser OAuth Login, Web OAuth Login** to **Yes**
* I use lates [PHP SDK](https://packagist.org/packages/facebook/php-sdk-v4)

-----

* Does Facebook have issues with `.space` domains when used in apps?
* Does anyone have a site with facebook login with long domain name like `.space` or `.production`, it works well?

**Comment by moldcraft** [comment]
Update: I noticed when I add in **Valid OAuth redirect URIs** `http://my-site.space/user/oauth/facebook` (note `http`, my site is `https`), then I get: `Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request`

**Comment by moldcraft** [comment]
Where else can I ask this question, is there any Facebook bug tracker?

**Comment by moldcraft** [comment]
Hm, I create on my localhost the `my-site-dev.space` domain. Then on facebook I configured a new app with that domain, and it works (for **Valid OAuth redirect URIs** I set `https://my-site-dev.space/`).

I tried the same for my live/real `mysite.space` domain: I delete the old app from facebook, create a new one, and it doesn't work, same error (wtf).

**Comment by moldcraft** [comment]
I setup the exact same domain (`myrealdomain.space`) on my localhost, with valid https certificate (taken from the live server) and it works. Why it doesn't work on live server? (it's the same code)

**Comment by moldcraft** [comment]
It's weird that my error message is not in english

```
Invalid redirect_uri: De opgegeven URL wordt niet toegestaan door de configuratie van de toepassing.
```

I am hosting my site on Digital Ocean, maybe they have something that changes/broke my requests to Facebook API?

**Comment by moldcraft** [comment]
> We do not have any proxy for requests to Facebook, your requests go directly from your droplet to Facebook. As they are returning the error at that point, I unfortunately do not have any sound advice for this.

**Comment by moldcraft** [comment]
On Monday-Tuesday I will move everything from DO to other server, and will see if it helps.

----

Anyway, I think this library has nothing to do with the problem, there is something wrong with my server.

If you have any idea what it may be, please leave a comment.

**Comment by moldcraft** [comment]
I added after [this line](https://github.com/facebook/facebook-php-sdk-v4/blob/72fe2861f75542e1d27dff2e9060af469a93970d/src/Facebook/Helpers/FacebookRedirectLoginHelper.php#L253)

```php
var_dump($_SERVER['HTTPS'], $redirectUrl); die;
```

and it printed

```
string(2) "on" 
string(395) "http://mysite.space/user/oauth/facebook?code=...
```

Note: **http**://mysite.space it must be **https**

I specified manually the redirect url

```php
$helper->getAccessToken('https://mysite.space/user/oauth/facebook')
```

and it finally works!

**Comment by SammyK** [comment]
Yes, detecting HTTPS that's behind a proxy can be particularly difficult. That's why you can overwrite the URL-detection logic in v5 by coding to the `UrlDetectionInterface` and injecting it into the `Facebook` service:

```php
use Facebook\Url\UrlDetectionInterface;

class MyFbUrlDetection implements UrlDetectionInterface
{
    public function getCurrentUrl()
    {
        // Do current URL detection logic here...
        return 'https://...';
    }
}

$fb = new Facebook\Facebook([
  // . . .
  'url_detection_handler' => new MyFbUrlDetection,
]);
```

I hope that helps others having this issue. :)

**Comment by moldcraft** [comment]
> detecting HTTPS that's behind a proxy can be particularly difficult

I don't see anything complicated [here](http://stackoverflow.com/a/7304205/1794248)

**Comment by SammyK** [comment]
For more involved setups, the `$_SERVER['HTTPS']` won't return the proper value if your TLS/SSL is being terminated at the load balancer for example. As far as your scripts are concerned on their non-TLS/SSL configuration, you're running HTTP.

I ran into this issue all the time when running a load balancer at AWS.

**Comment by moldcraft** [comment]
I have a similar configuration 

```
https -> nginx -> internalRequest:8080 -> apache2
```

* In `/etc/nginx/proxy_params` I set

    ```
    proxy_set_header X-Forwarded-Proto $scheme;
    ```

* In Apache I set

    ```
    <VirtualHost ...>
        # ...

        SetEnvIf X-Forwarded-Proto https HTTPS=on

        # ...
    </VirtualHost>
    ```

but somehow, on my installation, Symfony2 [generates](http://symfony.com/doc/current/book/routing.html#generating-absolute-urls) the right url, with `https`. I use that for redirect url

```php
$facebook->getRedirectLoginHelper()->getLoginUrl(
    $this->generateUrl('user_oauth_facebook', array(), UrlGeneratorInterface::ABSOLUTE_URL)
);
```

So Symfony2 can detect that I am using https but Facebook-SDK can't, one of them is wrong *(and I think it's SDK)*.

**Comment by SammyK** [comment]
> one of them is wrong

It's not that one is "wrong", it's that Symfony's HttpFoundation component has over 2,000 lines of code in the [`Request` entity](https://github.com/symfony/HttpFoundation/blob/master/Request.php) alone which can detect the current URL on a wide variety of environments. 

The SDK does a best-guess for 90% of the cases using [as little code as possible](https://github.com/facebook/facebook-php-sdk-v4/blob/5.0-dev/src/Facebook/Url/FacebookUrlDetectionHandler.php) and gives the user a way to overwrite the default logic if they fall outside of the 90% as I explained above. :)

But if you (or anyone reading this) has a suggestion to make the URL detection stuff even better without just copy/pasting the HttpFoundation, please send a PR! :)

**Comment by moldcraft** [comment]
Thank you

**Comment by mapicard** [comment]
My symptom was the famous 

> Error: Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings

After trying SO many things, manually providing my login_callback url on getAccessToken is what fixed it. ($helper->getAccessToken($my_fb_callback)).

It is surprising that this cause does not show up more when searching for this error.
Thanks a lot for sharing.

**Comment by yguedidi** [comment]
@mapicard thanks! When you don't provide a callback, the SDK will guess the current URL, this is the default behavior. Maybe there is an issue in either the detection, the documentation or behavor itself.
An idea for next major version could be to force prividing the redirect uri

**Comment by zaytechcloud** [comment]
Hi All, 
I want to set up facebook login with Radiusdesk wifi service. Is this possible through a localhost? Or it should require a VPS?  Please advice.. If possible give me a detailed solution or a reference document will be really helpful.
