### ISSUE TITLE
FacebookRequest, execute: method not found

### ISSUE THREAD

**Issue by itry-dev** [facebook/facebook-php-sdk-v4#477]
Hi,
I'm trying to get user friends using the simple script provided on developer's site, but FacebookRequest (if I take a look at the source code) doesn't have the execute method. 
So, how can I call graph api?

**Comment by SammyK** [comment]
See the latest example for [making a GET request with v5](https://developers.facebook.com/docs/php/howto/profilewithgraphapi/5.0.0) of the PHP SDK.

**Comment by itry-dev** [comment]
thank you
