### ISSUE TITLE
Error: 1 An unknown error has occurred.

### ISSUE THREAD

**Issue by antonellof** [facebook/facebook-php-sdk-v4#478]
What does error n. 1 mean? it occur often when post...

try {
  // Returns a `Facebook\FacebookResponse` object
  $response = $fb->post('/pageid/feed', $linkData, '{access-token}');
} catch(Facebook\Exceptions\FacebookResponseException $e) {
  echo 'Graph returned an error: ' . $e->getMessage();
  exit;
} catch(Facebook\Exceptions\FacebookSDKException $e) {
  echo 'Facebook SDK returned an error: ' . $e->getMessage();
  exit;
}

**Comment by SammyK** [comment]
Are you replacing `pageid` and `{access-token}` with your page ID and access token? What's the full error you're getting? See the [Graph API error codes](https://developers.facebook.com/docs/graph-api/using-graph-api/v2.4#receiving-errorcodes).

**Comment by antonellof** [comment]
Hi SammyK, sure i'm using some $vars instead pageid and access-token. The code works very well in 95% of times, but strangely sometimes give Error n. 1 $e->getCode() , An unknown error has occurred. $e->getMessage()

**Comment by SammyK** [comment]
Hmmm, that's strange. I'm wondering if your box is having intermittent connection issues?

**Comment by antonellof** [comment]
SammyK, i made several test. (I have a digital ocean box used for schedule my app users post, some php workers with beanstalkd queue), 1-2 months ago never had error 1. Since fb update too new api (min 2.0) i think they indroduced some hidden limit for concurrency api using. From my tests if i reduce the number of worker to 1 at time, i had no more errors 1, but if some api calls (from same user token) are done in the same moment error 1 occurs. Maybe could be the box connection to fb api ip that is filter... i dont now.

**Comment by gfosco** [comment]
Closing as this doesn't appear to be SDK related.
