### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by RushabhJoshi** [facebook/facebook-php-sdk-v4#479]
hey,
so far, I have no issue using this sdk 
but I am having trouble implementing pagination in (page) feeds.
Sorry if I'm asking silly question but,

I have a api for page feeds

```
GET /api/v1/feeds
```

Now I want to implement pagination on this api
lets assume this gives me 5 feeds. now I want next 5 feeds like

```
GET /api/v1/feeds?page=2
```

(previously i'd done by passing cursor in query string ***old sdk***)

I referred this link for implementing new style pagination
https://developers.facebook.com/docs/php/howto/example_pagination_basic/5.0.0

my function looks like(php codeigniter)

```php
public function feeds()
{
    $this->config->load('facebook');
    $this->library->load('facebook');
    $feeds = $this->facebook->getUserPageFeeds($page_access_token, $page_id);

    $this->response($feeds, 200);
}
```

my facebook library function
```php
public function getUserPageFeeds($access_token, $id)
{
    $this->fb->setDefaultAccessToken($access_token);
    $response = $this->fb->get("/{$id}/feeds");
    $feeds = $response->getGraphEdge()->asArray();

   return $feeds;
}
```

Thank you,

**Comment by SammyK** [comment]
You need to pass the `GraphEdge` object to the paginator. You're passing in an array since you're converting the results in the `getUserPageFeeds()` to an array with `->asArray();`

**Comment by RushabhJoshi** [comment]
I think ci pagination library is not that flexible

can I get next cursor and pass to the query string? (getNextCursor())

**Comment by SammyK** [comment]
The `GraphEdge` object is the cursor. What's the CI library you're using?

**Comment by SammyK** [comment]
But yes, you could [manually paginate](https://developers.facebook.com/docs/graph-api/using-graph-api/v2.4#paging) with the proper query params.

**Comment by RushabhJoshi** [comment]
Sorry I tried hard,
But 
```php
$graphEdge->getPreviousCursor();
graphEdge->getNextCursor();
$graphEdge->getTotalCount();
```
none of them working. returns null value

**Comment by RushabhJoshi** [comment]
$graphEdge->getMetaData();
worked for me,
Thanks sammy
