### ISSUE TITLE
Improve getFields method of Collection.php

### ISSUE THREAD

**Issue by jfradj** [facebook/facebook-php-sdk-v4#480]
The return of the method getFields (Collection.php line 72) should simply be:
```php
return $default
```

Indeed if I call the method (as it is right now) like that:
```php
$tz = $user->getField('timezone', 0);
```
`$tz` will be `null` instead of being equals to `0`

Cheers

**Comment by johnitvn** [comment]
I think that's not problem when you knew exactly type of default you can use operator '===' instead '=='

**Comment by SammyK** [comment]
Good call. Just sent PR #484 to fix this behavior. :) Thanks @jfradj!
