### ISSUE TITLE
Custom session storage in v5.x

### ISSUE THREAD

**Issue by wouterds** [facebook/facebook-php-sdk-v4#486]
Hi,

In the older version, 4, there used to be some comments in the `FacebookRedirectLoginHelper` class about overriding sessions if you wanted to store them somewhere else.

In the new version I don't see those anymore, but I assume this now needs to be done with `FacebookSessionPersistentDataHandler`, right? And then extend `Facebook` and override `getRedirectLoginHelper()` and use your own `FacebookSessionPersistentDataHandler`?

Or how is this supposed to go now?

Cheers,
Wouter

**Comment by gfosco** [comment]
I believe the right approach is to create your own handler which conforms to the `Facebook\PersistentDataInterface`, copy from the `FacebookSessionPersistentDataHandler`, and inject it when creating your `Facebook` instance... something like:

```
$fb = new Facebook\Facebook([
  'app_id' => '{app-id}',
  'app_secret' => '{app-secret}',
  'default_graph_version' => 'v2.4',
  'persistent_data_handler' => new MyDataHandler()
]);
```

**Comment by SammyK** [comment]
Yep! See the [`PersistentDataInterface` docs](https://developers.facebook.com/docs/php/PersistentDataInterface/5.0.0) for more info. :)

**Comment by wouterds** [comment]
Thanks guys!
