### ISSUE TITLE
Retrieving an App Access Token

### ISSUE THREAD

**Issue by trsteel88** [facebook/facebook-php-sdk-v4#490]
There doesn't seem to be any documentation for v5.x about how to retrieve an App Access Token. Is this possible in v5?

**Comment by SammyK** [comment]
The app access token is just a pipe-delimited concatenation of your app ID and app secret: `app_id|app_secret`. Here's [more info about access tokens](https://www.sammyk.me/access-token-handling-best-practices-in-facebook-php-sdk-v4).

**Comment by trsteel88** [comment]
Ah cool. thanks.
