### ISSUE TITLE
Sometimes redirects loop error happen

### ISSUE THREAD

**Issue by eedithz** [facebook/facebook-php-sdk-v4#492]
Hi,

My team are implementing facebook login for our company website, but sometimes we get too many redirects error shown on the browser.

"The page isn't redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete."

Sometimes it works normally though. do you have any sugestion about this?

Thanks,

**Comment by SammyK** [comment]
What is the URL you're using for the redirect URL in your app settings and PHP code?

**Comment by eedithz** [comment]
Hi SammyK, thanks for replying. Here is the redirect URL in my PHP code:
<pre> MYBASEURL."/facebook.php?action=login </pre>
However, redirect URL in app setting was blank. I am not sure if the problem is already resolved when i setup the URL in app setting since the problem only happen occasionally.

**Comment by gfosco** [comment]
In your application handling the redirect, check the various scenarios of how your application might respond.  If in some case you trigger a redirect to Facebook for login, that could be the problem.

If this happens reproducibly, please re-open with details.  Thanks.
