### ISSUE TITLE
Summary(true) Data missing in Graph

### ISSUE THREAD

**Issue by MikeeI** [facebook/facebook-php-sdk-v4#493]
As example it tried to get the Like Counts of each video of a page like this:

FacebookDevelopers/videos/?fields=likes.limit(1).summary(true),id,created_time&limit=5

In the GraphExplorer i get this for a video in the list
...
 "summary":  {
"total_count": 445,
"can_like": true,
 "has_liked": false}
...

but in the Graph this data is missing. How can i get this "debugging data". Tried to bypass this "bug", but it is not feasible to make thousands of request for a page with a lot of videos if i can do it with 40 or less. 

Is there a timeline for this feature, so i can wait and not have to switch to Facebook PHP v4 oder manual Requests.

Greetings Mikeel

**Comment by SammyK** [comment]
In v5 of the PHP SDK you can get that data on the `GraphEdge` with the [`getMetaData()` method](https://developers.facebook.com/docs/php/GraphEdge/5.0.0#get-meta-data).

```php
$response = $fb->get('FacebookDevelopers/videos/?fields=likes.limit(1).summary(true),id,created_time&limit=5');

$videos = $response->getGraphEdge();

foreach ($videos as $video) {
    $metadata = $video['likes']->getMetaData();
    var_dump($metadata);
    // . . .
}
```
