### ISSUE TITLE
Unable to detect if a datetime field is date-only

### ISSUE THREAD

**Issue by valtzu** [facebook/facebook-php-sdk-v4#495]
Since is_date_only is deprecated as of Graph API v2.4, and f.e. start_time of an event is always casted to DateTime, there is no way to detect whether date actually has the time attribute.

Basically this means that response from the event endpoint like
```
{
   "start_time": "2015-09-10T00:00:00+0300",
   "id": "1000000000000000"
}
```

is interpreted identically compared to
```
{
   "start_time": "2015-09-10",
   "id": "1000000000000000"
}
```

Of course, you can't just draw a conclusion "If event starts at 00:00:00, it has no time set", since some events may start at that time.

To overcome the issue, access to uncasted values would be needed, and I don't think that's possible at the moment outside the SDK.

**Comment by SammyK** [comment]
Yeah, I'm not a fan of the auto `DateTime` casting. Maybe we can kill that in v6? :)

For now you can get the response data as a plain-old array from the `FacebookResponse` with:

```php
$data = $response->getDecodedBody();
```

I hope that helps! :)

**Comment by valtzu** [comment]
Well, that's what I was afraid of. In my opinion, the [fields declared as string in the official API documentation](https://developers.facebook.com/docs/graph-api/reference/event) should not be treated as ```DateTime```. For example, an event has field ```start_time```, which is declared as ```string```, and a field named ```updated_time```, which is declared as ```datetime``` in the API documentation. I think those should be taken into account, and autocast accordingly. :)

For now, I guess I'll just have to stick with a workaround of somekind.

**Comment by SammyK** [comment]
Agree. :) Unfortunately since this would be a BC, it'll have to be slated for v6. But that's certainly something we need to take care of in the next major version. Thanks for reporting this issue!

**Comment by gfosco** [comment]
Definitely willing to accept that as a PR for v6.  Interesting find, thanks! :+1:
