### ISSUE TITLE
Removal of development & testing files using .gitattributes

### ISSUE THREAD

**Issue by EmanueleMinotto** [facebook/facebook-php-sdk-v4#507]
Considering the number of downloads and to speed up the download, what about the removal of development & testing files using `.gitattributes`?

Reference: https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production/

**Comment by gfosco** [comment]
I'm supportive of this.. send in a PR :+1:

**Comment by SammyK** [comment]
:+1: Good stuff

**Comment by SammyK** [comment]
@EmanueleMinotto Let me know if you'd like me to take care of this or if you just want to knock it out.

**Comment by EmanueleMinotto** [comment]
@SammyK I'm going to send a PR, thanks :)
