### ISSUE TITLE
FacebookResponse->getETag() returns null for batched response

### ISSUE THREAD

**Issue by scramblor** [facebook/facebook-php-sdk-v4#521]
I can get all the headers and find the ETag there, however the utility getETag() function does not work.

It looks like the headers value on a FacebookResponse is constructed differently depending if it is an unbatched or part of a batched request.

Dumping there headers I can see unbatched requests are an associative array eg-
['Header1Name' = 'Header1Value', ...]

Batched request headers are a list of key value entires eg-
[['name' = 'Header1Name', 'value' = Header1Value], ...]

I'm not sure if the appropriate fix would be to update the way the FacebookResponse is constructed so that the headers structure is consistent or to update the accessor methods to handle the difference in structures.

**Comment by SammyK** [comment]
Nice find! I just pushed up a fix in #523 :)
