### ISSUE TITLE
Error 368 when posting to my feed

### ISSUE THREAD

**Issue by Eke** [facebook/facebook-php-sdk-v4#528]
I'm trying to publish post from my website to my facebook wall with FacebookRequest and i am getting  this response ` error 368 with message: Your message couldn't be sent because it includes content that other people on Facebook have reported as abusive.`

I know what does this error mean, but we think we were blocked by mistake. can you please help me and point me a way we can deal with this situation? we were not able to find any solution online. Can we do some fixes or something on our side to fix this issue?

**Comment by gfosco** [comment]
Hi.  That's an interesting issue, but unrelated to the SDK.  Please report this issue through developers.facebook.com to see if you can get the URL un-blacklisted.  Thanks.
