### ISSUE TITLE
Broken for large app Id values

### ISSUE THREAD

**Issue by ghaugen** [facebook/facebook-php-sdk-v4#532]
The SDK is broken in a few places for large App Ids that get formatted in exponential notation by PHP.

I've patched my version locally with the following fixes:

OAuth2Client.php line 138 and 288:
            'client_id' => sprintf("%.0f", $this->app->getId()),

FacebookSignedRequestFromInputHelper.php line 160:

        $cookieName = sprintf('fbsr_%.0f', $this->app->getId());
        
        if (isset($_COOKIE[$cookieName])) {
            return $_COOKIE[$cookieName];
        }

Hopefully someone will pick this up and incorporate it in the code.

**Comment by SammyK** [comment]
Can you provide an example ID that breaks the functionality?

**Comment by yguedidi** [comment]
Ids should be string

**Comment by ghaugen** [comment]
Yeah it broke for me since I assigned a numeric Id:

$config->facebook->appId = 1654110344860325;

        $fb = new \Facebook\Facebook([
            'app_id' => $config->facebook->appId,

Might be worth checking for this in the SDK code, since I don't think I'll be the last one to try using a numeric value.

**Comment by gfosco** [comment]
Yeah, OAuthClient should definitely not be formatting this as a number... will accept the first PR to fix it. :)

**Comment by SammyK** [comment]
Closing since this will be fixed when #556 gets merged. :)
