### ISSUE TITLE
Signed Request missing from production server, but not from staging

### ISSUE THREAD

**Issue by karankashyap** [facebook/facebook-php-sdk-v4#534]
I have 2 domains - abc.com (staging), xyz.com (production) on different servers, no relation whatsoever. The app I have created runs in the page tab. With the __exact__ same code on staging and production, I'm getting this on (staging - abc.com)

`Array ( [algorithm] => HMAC-SHA256 [expires] => 144*****00 [issued_at] => 144*****5 [oauth_token] => ***** [page] => Array ( [id] => 1*****263 [admin] => 1 ) [user] => Array ( [country] => in [locale] => en_US [age] => Array ( [min] => 21 ) ) [user_id] => 103*****48 )    `

This is the most important part: 
__[page] => Array ( [id] => 123462946898735463)__

To run the app, I need the page id the most which I'm getting on the staging. 

__Problem:__ On production I'm getting nothing from the signed request within the page tab, but when I hit the url directly (out of facebook), the signed request shows up (without the page id of course). 
I am also getting the signed request on production in $_POST inside the page tab but not as an object where I can get the page ID from. 
The app is highly dependable on page id. So, it has to run in the page tab which isn't giving me the signed request. 

__Config:__ Page and app are both live. The page tab url is https and ends with the file name index.php

I can't figure out the issue. I'm thinking it is domain specific but even if it is, what is the setting that causes this behaviour? Or if it is not, what should I do to resolve this? Any help would be appreciated.

**Comment by SammyK** [comment]
The signed request should only be available via the cookie set via the Javascript SDK and the `signed_request` param sent via POST in the canvas. So it shouldn't be accessible outside of the canvas unless you are obtaining it from the cookie.

Can you post the code snippets that are relevant to your issue?

**Comment by SammyK** [comment]
Feel free to chime back in if you're still having an issue with this. :)
