### ISSUE TITLE
post_id returned for photos, but not videos

### ISSUE THREAD

**Issue by marcusds** [facebook/facebook-php-sdk-v4#536]
Why the inconsistency?

With a photo this code will contain post_id, but for a video it will not.

```
$response = $Facebook->post('/me/photos', $data, $token); // Or videos
$graphNode = $response->getGraphNode();
echo $graphNode['post_id'];
````

When posting a video it will only come back with ID.

**Comment by SammyK** [comment]
The SDK just returns the response it gets from the Graph API. See [user/photos](https://developers.facebook.com/docs/graph-api/reference/v2.5/user/photos#Creating) and [user/videos](https://developers.facebook.com/docs/graph-api/reference/v2.5/user/videos/#Creating). You can create a [bug report for the Graph API](https://developers.facebook.com/bugs/).
