### ISSUE TITLE
Graph error validating client secret

### ISSUE THREAD

**Issue by zorow** [facebook/facebook-php-sdk-v4#538]
Im trying to implement the  facebook login via the php sdk ive set the correct appid and app secret and also in the dashboard ive set the correct appdomain and site url yet still it cant give me an access token kindly assist

**Comment by SammyK** [comment]
Can you post any relevant errors and snippets of code that are causing the error?

**Comment by zorow** [comment]
in accessing the access token is the place the error get generated and im sure ive triple checked the client secret for validity
try {

	$accessToken = $helper->getAccessToken();

} catch(Facebook\Exceptions\FacebookResponseException $e) {
	// When Graph returns an error
	echo 'Graph returned an error: ' . $e->getRawResponse();
	exit;
} catch(Facebook\Exceptions\FacebookSDKException $e) {
	// When validation fails or other local issues
	echo 'Facebook SDK returned an error: ' . $e->getMessage();
	exit;
}

**Comment by xero88** [comment]
Hi,

What are the returned error ?

**Comment by zorow** [comment]
it says Graph error: couldn't verify client secret

**Comment by zorow** [comment]
This is the exact messge

Graph returned an error: {"error":{"message":"Error validating client secret.","type":"OAuthException","code":1,"fbtrace_id":"F0n\/KYH+Z5K"}}

**Comment by gfosco** [comment]
You're sure you're setting the app_secret param when creating the Facebook instance?

**Comment by zorow** [comment]
yeah its giving me this error
raph returned an error: {"error":{"message":"Error validating client secret.","type":"OAuthException","code":1,"fbtrace_id":"GKSG9vhaRCq"}}

**Comment by SammyK** [comment]
Can you `var_dump()` your app ID and secret directly from the SDK to make sure they are all correct? Sometimes they can get messed up from the config files to when they make it to the SDK.

```php
$app = $fb->getApp();

var_dump($app->getId(), $app->getSecret());
```

http://stackoverflow.com/a/11546136/443479

**Comment by biscolab** [comment]
Copy correctly the app secret. The last piece could be hidden in a second line

<img width="423" alt="schermata 2016-03-18 alle 16 21 13" src="https://cloud.githubusercontent.com/assets/9263090/13882510/01ab0080-ed26-11e5-9bb1-70ac0aa0037a.png">

**Comment by SammyK** [comment]
I'm going to close this for now, but feel free to chime back in if you're still having an issue with this. :)
