### ISSUE TITLE
Cross-site request forgery validation failed. Required param "state" missing.

### ISSUE THREAD

**Issue by xero88** [facebook/facebook-php-sdk-v4#539]
Hi,

I have implemented, months ago, the login facebook. All was ok. But now, I get this : 

Facebook SDK returned an error: Cross-site request forgery validation failed. Required param "state" missing.

Please help, I'm search for 5 hours, I don't know how to solve this....

I'm on Zend Framework, I use the Facebook-sdk 5.1.2 with composer

Thank you

Edit: I followed https://www.sammyk.me/upgrading-the-facebook-php-sdk-from-v4-to-v5

**Comment by yguedidi** [comment]
@xero88 Can you please add an explicit `sesion_start()` before calling the SDK? It should solve the problem.
@gfosco Once I have some time, I'll send a PR that will definitely solve this bug!!!

**Comment by gfosco** [comment]
Thanks @yguedidi !

**Comment by kongnakornna** [comment]
Facebook SDK returned an error: Cross-site request forgery validation failed. Required param "state" missing from persistent data.

**Comment by yguedidi** [comment]
@kongnakornna I think there are some issue with your PHP session that it doesn't store the state, so not an SDK issue. StackOverflow may help ;)
