### ISSUE TITLE
Where do you report typos in docs?

### ISSUE THREAD

**Issue by irazasyed** [facebook/facebook-php-sdk-v4#541]
Not sure where i could report the typo i came across.

Maybe someone who knows could pass on to the appropriate team:
https://developers.facebook.com/docs/javascript/howto/angularjs#handling-callbacks

First para, there's a typo:
> The `Facbeook` SDK for JavaScript does not support the concept of promises. As a workaround you can bundle your Facebook for JavaScript SDK calls (for example) into a service:

Should be `Facebook` obviously.

**Comment by gfosco** [comment]
You should be able to report this as a bug through the facebook developer portal, https://developers.facebook.com/bugs
