### ISSUE TITLE
Facebook SDK returned an error: Connection timed out after 10001 milliseconds

### ISSUE THREAD

**Issue by AshutoshKumarAnand** [facebook/facebook-php-sdk-v4#543]
Getting this Error on my website even when Curl is also enabled and PHP version is 5.6

**Comment by SammyK** [comment]
Sounds like you're behind a slow connection or the server is unable to communicate with Facebook.

**Comment by AshutoshKumarAnand** [comment]
@SammyK  It is not slow connection at all, everything else is working fine but why it could not communicate with Facebook ?

**Comment by gfosco** [comment]
There's unfortunately not enough information here for us to determine your problem, and it is unlikely to be related to the SDK itself.  If you can troubleshoot further or provide more detailed information, it may point to the real cause of the problem.  Thanks.

**Comment by vaseemkhan** [comment]
I have same problem, Plz help anybody. I am tries to change connection time out 10 to 60 but after that problem remain same. "Facebook SDK returned an error: Connection timed out after 60001 milliseconds".

**Comment by SaeedSoltoon** [comment]
@vaseemkhan @AshutoshKumarAnand  hi,
do you solve your problem? if yes could you please guide me how to solve it, because i have same problem too.

**Comment by SammyK** [comment]
@vaseemkhan @SaeedSoltoon You might want to try and [increase the default time-outs](https://www.sammyk.me/how-to-inject-your-own-http-client-in-the-facebook-php-sdk-v5#increasing-the-default-timeouts). Hope that helps! :)

**Comment by deepakdsm24** [comment]
I have same problem, please help anybody

**Comment by gaurav2695** [comment]
SammyK i am also getting the error "Facebook SDK returned an error: Resolving timed out after 10515 milliseconds"

and my code is this (just ignore the APPID and APP Secret)
and i am using xampp server for hosting my website from localhost, i want to retrieve the user basic info also.

`<?php
session_start();
require_once __DIR__ . '/Facebook/autoload.php';

$fb = new Facebook\Facebook([
  'app_id' => APPID,
  'app_secret' => APP Secret,
  'default_graph_version' => 'v2.4',
  ]);

$helper = $fb->getRedirectLoginHelper();

$permissions = ['email']; // optional
	
try {
	if (isset($_SESSION['facebook_access_token'])) {
		$accessToken = $_SESSION['facebook_access_token'];
	} else {
  		$accessToken = $helper->getAccessToken();
	}
} catch(Facebook\Exceptions\FacebookResponseException $e) {
 	// When Graph returns an error
 	echo 'Graph returned an error: ' . $e->getMessage();

  	exit;
} catch(Facebook\Exceptions\FacebookSDKException $e) {
 	// When validation fails or other local issues
	echo 'Facebook SDK returned an error: ' . $e->getMessage();
  	exit;
 }

if (isset($accessToken)) {
	if (isset($_SESSION['facebook_access_token'])) {
		$fb->setDefaultAccessToken($_SESSION['facebook_access_token']);
	} else {
		// getting short-lived access token
		$_SESSION['facebook_access_token'] = (string) $accessToken;

	  	// OAuth 2.0 client handler
		$oAuth2Client = $fb->getOAuth2Client();

		// Exchanges a short-lived access token for a long-lived one
		$longLivedAccessToken = $oAuth2Client->getLongLivedAccessToken($_SESSION['facebook_access_token']);

		$_SESSION['facebook_access_token'] = (string) $longLivedAccessToken;

		// setting default access token to be used in script
		$fb->setDefaultAccessToken($_SESSION['facebook_access_token']);
	}

	// redirect the user back to the same page if it has "code" GET variable
	if (isset($_GET['code'])) {
		header('Location: ./');
	}

	// getting basic info about user
	try {
		$profile_request = $fb->get('/me?fields=name,first_name,last_name,email');
		$profile = $profile_request->getGraphNode()->asArray();
	} catch(Facebook\Exceptions\FacebookResponseException $e) {
		// When Graph returns an error
		echo 'Graph returned an error: ' . $e->getMessage();
		session_destroy();
		// redirecting user back to app login page
		header("Location: ./");
		exit;
	} catch(Facebook\Exceptions\FacebookSDKException $e) {
		// When validation fails or other local issues
		echo 'Facebook SDK returned an error: ' . $e->getMessage();
		exit;
	}
	
	// printing $profile array on the screen which holds the basic info about user
	print_r($profile);

  	// Now you can redirect to another page and use the access token from $_SESSION['facebook_access_token']
} else {
	// replace your website URL same as added in the developers.facebook.com/apps e.g. if you used http instead of https and you used non-www version or www version of your website then you must add the same here
	$loginUrl = $helper->getLoginUrl('http://localhost/stest/', $permissions);
	echo '<a href="' . $loginUrl . '">Log in with Facebook!</a>';
}`

**Comment by liangyawei** [comment]
I have the same problem,who can help me slove this ?

**Comment by ashutoshpw** [comment]
The problem is that some shared hosts disabled scraping and due to which you cannot access facebook graph API endpoint and be getting this error. I will suggest to use the direct CURL APIs to check if you are able to access facebook api endpoint

**Comment by gautamsinh** [comment]
As I know at the end this SDK also call a CURL
