### ISSUE TITLE
Facebook\HttpClients classes should offer an interface to configure them properly

### ISSUE THREAD

**Issue by pr0nbaer** [facebook/facebook-php-sdk-v4#547]
Hello and greetings from bavaria ;),

I'm having trouble configuring the library to manage Facebook API calls over proxy. I tried to override the default http client handler (using the configuration array key <code>http_client_handler</code> of <code>Facebook\Facebook</code>) with a custom instance of the CUrl http client to set some basic CURLOPT_* options:
```php
$curl = new \Facebook\HttpClients\FacebookCurl();
$curl->init();
$curl->setopt(CURLOPT_PROXY, '<best proxy of the world goes here>');
$httpClient = new \Facebook\HttpClients\FacebookCurlHttpClient($curl);

$fb       = new \Facebook\Facebook(
    [
        'app_id'                => '...',
        'app_secret'            => '...',
        'default_graph_version' => 'v2.5',
        'default_access_token'  => '...',
        'http_client_handler' => $httpClient
    ]
);
```
The problem: the Facebook\HttpClients\FacebookCurlHttpClient class (and every other of the HTTP client classes) always override the given options with hardcoded options (see https://github.com/facebook/facebook-php-sdk-v4/blob/master/src/Facebook/HttpClients/FacebookCurlHttpClient.php#L103-L124).

One solution would be to create a custom http client class and override the given method above, but i guess it would be better to offer an interface for developers to actually change the options with the default classes.

Best regards,

pr0nbaer.

**Comment by SammyK** [comment]
Hey @pr0nbaer! You can just add your own curl options pretty easily if you extend the `FacebookCurlHttpClient` with your own handler:

```php
class MyCurlClient extends \Facebook\HttpClients\FacebookCurlHttpClient
{
    public function openConnection($url, $method, $body, array $headers, $timeOut)
    {
        parent::openConnection($url, $method, $body, array $headers, $timeOut);
        $this->facebookCurl->setopt(CURLOPT_PROXY, '<best proxy of the world goes here>');
    }
}
```

For more details, I wrote a blog post on [overwriting the default HTTP client](https://www.sammyk.me/how-to-inject-your-own-http-client-in-the-facebook-php-sdk-v5). Hope that helps! :)

**Comment by pr0nbaer** [comment]
@SammyK As I said above: One solution would be to create a custom http client class and override the given method above, but i guess it would be better to offer an interface for developers to actually change the options with the default classes.

But thanx for your reply :)
