### ISSUE TITLE
Every login causing this error

### ISSUE THREAD

**Issue by net32** [facebook/facebook-php-sdk-v4#550]
Graph returned an error: This authorization code has been used.

**Comment by rpopentiu** [comment]
Are you converting the short-lived token into a long-lived token?

**Comment by net32** [comment]
como faço isso, você tem código ?

**Comment by net32** [comment]
Solved! 
i found two problems on my system, first date.timezone wrong, second using $helper->getSession()->getToken() change to $helper->getSession();

**Comment by sivapc** [comment]
Set time zone like this will solve the issue
date_default_timezone_set('America/Los_Angeles');
