### ISSUE TITLE
Get all comments from post returns empty value

### ISSUE THREAD

**Issue by Shamonshamonsha** [facebook/facebook-php-sdk-v4#551]
Full is described on this thread
http://stackoverflow.com/questions/35145680/get-all-comments-for-a-post-in-facebook-graph-api

**Comment by SammyK** [comment]
This is most likely a permissions issue when you get an empty array when expecting actual data. Try adding `debug=true` to your request to get debug data. Also make sure the root ID is a valid node. Use the Graph API Explorer to poke around too: https://developers.facebook.com/tools/explorer

**Comment by SammyK** [comment]
I'm going to close this for now, but feel free to chime back in if you're still having an issue with this. :)
