### ISSUE TITLE
Basic problems

### ISSUE THREAD

**Issue by Mandaricks** [facebook/facebook-php-sdk-v4#557]
Hi,

I own a domain service hosted at leadhoster.com, and they say that is not possible to install Composer for me to have this script running there. Also, I don't have a console to type the commands as instructed. I am running Windows 10, and didn't see any program that opens a command shell to give orders to my server.
I know that there are two silly question, but I am alone trying to build a service and need to pass by this security issue, the login, as fast as possible, to deal with bigger issues ahead. Can you give me any tip on how to deal with that? Thanks!

**Comment by michaelmbowyer** [comment]
@Mandaricks, Please see the section in the documentation 'Manually installing (if you really have to). This link should take you to that section in the documentation:  [https://developers.facebook.com/docs/php/gettingstarted#install-manually](url)

**Comment by SammyK** [comment]
Thanks for helping out on this one @michaelmbowyer! :)
