### ISSUE TITLE
GET request in v5

### ISSUE THREAD

**Issue by Hamzeh-Ahmad** [facebook/facebook-php-sdk-v4#559]
# GET request in v5
Hi,
Am not sure if its a bug on its intentional by design.
```
$response = $fb->get('/me', '{access-token}');
```

If I want to specify the params (fields) I want to get, for example get message array:

```
$fb = new Facebook\Facebook([/* . . . */]);
$fb->get("/$messageId/", ['fields' => "id,created_time,tags,from,to,message,shares,subject,attachments", $accessToken], $facebookAccount['page_token']);
```

It wont work, it will give an error about access token, however the following work perfect:
```
$fb->get("/$messageId?fields=id,created_time,tags,from,to,message,shares,subject,attachments", $accessToken]);
```

I found in Facebook/Facebook.php line 333, that params are not passed to function get, and always send as init value of empty array:
```
public function get($endpoint, $accessToken = null, $eTag = null, $graphVersion = null){
     return $this->sendRequest(
         'GET',
         $endpoint,
         $params = [],
         $accessToken,
         $eTag,
         $graphVersion
     );
}
```
so is this a bug or by design ?

**Comment by EmanueleMinotto** [comment]
Hi @Hamzeh-Ahmad, please format the code following the examples, or will be hard to understand it
https://guides.github.com/features/mastering-markdown/#examples

**Comment by Hamzeh-Ahmad** [comment]
@EmanueleMinotto foramted, thank for notifying

**Comment by SammyK** [comment]
This is by design. See #384. The public API for this will probably change in the next major version. :)

**Comment by Hamzeh-Ahmad** [comment]
@SammyK Thanks for the help :)
