### ISSUE TITLE
Is it safe to migrate to v5 (API 2.5)

### ISSUE THREAD

**Issue by Hamzeh-Ahmad** [facebook/facebook-php-sdk-v4#561]
Is it safe to migrate to v5 (API 2.5), even if there is breaking changes in the future?
any recommendations please :)

**Comment by SammyK** [comment]
When you upgrade to v5 of the PHP SDK, you can set the `default_graph_version` to whatever you app is currently using. Once you've upgraded the SDK, you can change the Graph version to v2.5 and test the app to ensure everything is still working. :)

**Comment by Hamzeh-Ahmad** [comment]
@SammyK  that fair enough, thank you :)
