### ISSUE TITLE
Dublicated Post question

### ISSUE THREAD

**Issue by Hamzeh-Ahmad** [facebook/facebook-php-sdk-v4#562]
Hello Good people, 
we are facing an issue with a promoted video where facebook API sending us a link for the original video but it also sending us another 5 links, please advice, thank you.

**Comment by SammyK** [comment]
Hey @Hamzeh-Ahmad! Can you send an example of the response from the Graph API and any snippets of code you're using to get the response? :)

**Comment by Hamzeh-Ahmad** [comment]
Hi SammmyK, 

I no longer using this its been a while, I will close this ticket now and as soon as I face this problem , Iwill reopen it
