### ISSUE TITLE
Facebook Graph API,data fetch failure.(code 1, subcode null)

### ISSUE THREAD

**Issue by jestinnt** [facebook/facebook-php-sdk-v4#563]
Hello..
Im from data analytic field and and deals with web source data, such as facebook ,twitter etc.We pull data from the social media,analyze it and makes reports out of it.

Issue:After importing the new restfb API into the code,im not able to pull full data from a facebook page,in JAVA

Observations:

With the new API ,I am able to pull data only from pages with less posts,comments and likes.When i give the URL of a fb page wth higer posts ,likes and comments ,it throws an error saying
"com.restfb.exception.FacebookGraphException: Received Facebook error response of type : Please reduce the amount of data you're asking for, then retry your request (code 1, subcode null)"

So I kept a limit for the amount of data being pulled, which eventually showed some improvements,but not for all pages..For pages with thousands of posts and comments,im still getting the same error.

Im using paging technique,where im fetching first 100 posts,and then has a link for the next 100 and so on. 

is it because of the multiple requests that we are sending through the same access token and all at the same time??

Please advice.

**Comment by Hamzeh-Ahmad** [comment]
@jestinnt if you are using batch request, you are limited to 50 requests at once, am not sure how you send the requests to Facebook, but try to send 50 instead of 100, also check the rate limit of your requests.

**Comment by SammyK** [comment]
Thanks for chiming in on this one @Hamzeh-Ahmad!

@jestinnt - If you're still having issues with this feel free to chime back in! :)
