### ISSUE TITLE
[v5] Login with FB - long execution time

### ISSUE THREAD

**Issue by Innomme** [facebook/facebook-php-sdk-v4#567]
Hello,

I'm trying to integrate my app with Facebook login. After downloading and installing SDK I followed this example - https://developers.facebook.com/docs/php/howto/example_facebook_login
Everything works fine but IMO it is slow.

Basic login (https://developers.facebook.com/docs/php/howto/example_facebook_login)
Total Execution Time  	1.3998 (fb-callback.php)

Login and getting some data - fb-callback.php from example and one extra line
`$response = $fb->get('/me?fields=id,name,picture', $accessToken);`
Total Execution Time  	2.0653

I tried even with raw php files, without any FW, checked also on different servers - result are very similar. It is supposed to be that slow?

**Comment by SammyK** [comment]
Hey @Innomme! The response times will vary depending on many variables. But a 2 second response time is not unheard of at certain times of the day. :)
