### ISSUE TITLE
Limit api request with Facebook Connect

### ISSUE THREAD

**Issue by JoanIzquierdo** [facebook/facebook-php-sdk-v4#569]
Thanks for the PHP SDK. One question please. I am using the Facebook Connect and after I execute the next sentence to obtain some data client as name or email.

$response = $fb->get('/me', '{access-token}');

Do you know if there are any limit with this sentence? Is there a new limitations between PHP SDK v4 and v5? .. or, is there a new limitation between Graph API v.2.2 and v2.5?

In v4 I used the nexts instruccions:

$session = new FacebookSession( $session->getToken() );
$request = ( new FacebookRequest( $session, 'GET', '/me' ) )->execute();
$user_profile = $request->getGraphObject()->asArray();

.. and I didn't had any problem and now it seems that I have a problem 200 requests.

Thanks,

**Comment by SammyK** [comment]
Hey @JoanIzquierdo! There aren't any limitations built into the PHP SDK's. Any limitations would be coming from the Graph API directly. You can see if your app is [reaching the rate limit from the app dashboard](https://developers.facebook.com/docs/graph-api/advanced/rate-limiting). :)
