### ISSUE TITLE
Facebook SDK returned an error: Cross-site request forgery validation failed on localhost

### ISSUE THREAD

**Issue by faizytech** [facebook/facebook-php-sdk-v4#572]
Hi Guys i really need help.
i am using Xampp server locally on my windows based pc. i am OAuth dialog is working and returning successfully but received this error on callback page.
Facebook SDK returned an error: Cross-site request forgery validation failed. Required param "state" missing.

i have tried session_start already.
kindly guide me
Thanks

**Comment by sachintaware** [comment]
http://stackoverflow.com/questions/31347341/the-state-param-from-the-url-and-session-do-not-match

http://stackoverflow.com/questions/32029116/facebook-sdk-returned-an-error-cross-site-request-forgery-validation-failed-th

This is a long standing issue and here's a quick fix.You need to enable sessions and it should work.
Refer to both the SO threads for reference. All the best

**Comment by mantissefr** [comment]
Hello,

@nanangkoesharwanto

Thanks to the messages raised by mr. Taware, I think you should use the option :

"persistent_data_handler"=>"session"

See there for more information,

http://stackoverflow.com/questions/32029116/facebook-sdk-returned-an-error-cross-site-request-forgery-validation-failed-th

-----Message d'origine-----
De : "Sachin Taware" <notifications@github.com>
Envoyé : ‎14/‎04/‎2016 09:47
À : "facebook/facebook-php-sdk-v4" <facebook-php-sdk-v4@noreply.github.com>
Objet : Re: [facebook/facebook-php-sdk-v4] Facebook SDK returned an error:Cross-site request forgery validation failed on localhost (#572)

http://stackoverflow.com/questions/31347341/the-state-param-from-the-url-and-session-do-not-match
http://stackoverflow.com/questions/32029116/facebook-sdk-returned-an-error-cross-site-request-forgery-validation-failed-th
This is a long standing issue and here's a quick fix.You need to enable sessions and it should work.
Refer to both the SO threads for reference. All the best

**Comment by nanangkoesharwanto** [comment]
thank alot for your attention @mantissef,
i did that method before, and made my laravel (5.2) unstable.
sometimes it made lost connection, ajax didn't run, return to another route
didn't work, etc.
but, my last experiment, changing the script in the file, makes everything
run well.

again, thank you very much, and I will wait for the response.

**Comment by SammyK** [comment]
See: https://github.com/facebook/facebook-php-sdk-v4/issues/470#issuecomment-212561488 :)
