### ISSUE TITLE
Merge strategy

### ISSUE THREAD

**Issue by SammyK** [facebook/facebook-php-sdk-v4#575]
Hey @yguedidi! Just to make sure we're on the same page with merging the open PR's and tagging - do you want to have the honors of merging or tagging or you want me to? I just don't want us both tagging out of sync. :)

Since there are a quite a few PR's, you think we should merge them all and tag a new `MINOR` version or should we tag some under `PATCH` first and the rest under a `MINOR` tag?

**Comment by yguedidi** [comment]
You can merge, but each PR need at least a :+1: from the other one, and we can't merge our PRs, they must be merged by the other, what do you think about this?
About pending PRs, everything that goes to a patch version must be merged first, to let most users take benefits of it. What about using Github's milestones feature for that?
Finally about tagging releases, I can let you that honor, I'll to my best to help you when needed with my :+1: 's haha ;)

**Comment by SammyK** [comment]
Sounds good! I'll hopefully get some time to give the repo some TLC this weekend. :)
