### ISSUE TITLE
Tagged PR's with proposed SemVer release

### ISSUE THREAD

**Issue by SammyK** [facebook/facebook-php-sdk-v4#576]
Hey @yguedidi! I've gone through and tagged the pending PR's with the SemVer release I think they should fall under. Can you do a quick review and see if we need to change any of them? :)

**Comment by SammyK** [comment]
Ping @yguedidi :)

**Comment by yguedidi** [comment]
@SammyK Oups, I checked twenty days ago, but it seems I forgot to post a comment haha.

I agree with you about in which release each PR will fall under.

But for me it looks overkill to use GitHub tags for that, we can just use milestones without due date, like with the v6.0 one. (a 5.2.0 milestone for minor PRs, a 5.1.4 one for patchs)

**Comment by SammyK** [comment]
Good call - thanks man! :)
