### ISSUE TITLE
Regarding (#200) The user hasn't authorized the application to perform this action

### ISSUE THREAD

**Issue by helloarpitgshah** [facebook/facebook-php-sdk-v4#577]
Hey,

Hope you are doing good.

Thanks for the Facebook SDK, I have error while posting the message at user's feeds.

I have recently Approved: publish_actions from the Facebook. I have created on textarea to user to post message.

Whenever I am trying to post the message from different user then it got me 
(#200) The user hasn't authorized the application to perform this action

I am using following code to post the message,

$response = $fb->post('/me/feed', $data, $accessToken);

Can you please help me asap?

Thanks,
Arpit G Shah

**Comment by SammyK** [comment]
Hey @helloarpitgshah! Are you using the same access token that has the `publish_actions` permission? You can use the [token debugger](https://developers.facebook.com/tools/debug/accesstoken/) to make sure. This should allow you to post on the person's wall who authenticated the app and no one else's. Also check out the [`/user/feed` endpoint docs](https://developers.facebook.com/docs/graph-api/reference/v2.6/user/feed) to make sure everything else is good. Hope that helps! :)
