### ISSUE TITLE
Delete Post from Facebook Profile

### ISSUE THREAD

**Issue by anieshjoseph** [facebook/facebook-php-sdk-v4#580]
How can I delete a post from facebook profile ?  I have posted to facebook using following code and received an id after the action.
`    
    
    $fb = new Facebook\Facebook([
      'app_id' => $facebook_app_config['client_id'],
      'app_secret' => $facebook_app_config['client_secret'],
      'default_graph_version' => 'v2.2',
      ]);

    $linkData = [
      'link' => 'http://www.site.com/info.php?id=113',
      'message' => 'Message for testing purpose..'
      ];

    try {
      // Returns a `Facebook\FacebookResponse` object
      $response = $fb->post('/me/feed', $linkData, $facebook_user_info['facebook_access_token']);
    } catch(Facebook\Exceptions\FacebookResponseException $e) {
      echo 'Graph returned an error: ' . $e->getMessage();
      exit;
    } catch(Facebook\Exceptions\FacebookSDKException $e) {
      echo 'Facebook SDK returned an error: ' . $e->getMessage();
      exit;
    }

    $graphNode = $response->getGraphNode();

    echo 'Posted with id: ' . $graphNode['id'];`

**Comment by gfosco** [comment]
According to the graph api documentation, you can send a DELETE method request to /{post-id}.

```
$fb->delete('/' . $graphNode['id']);
```

**Comment by anieshjoseph** [comment]
Thank you for the answer. 

Here is the working code in my case. Your code shows error because there is no access token. 

`$response =   $fb->delete('/'.$graphNode['id'] ,array(), $facebook_access_token);`
