### ISSUE TITLE
Reopen:  Getting different values for $_SESSION["FBRLH_state"] and $_GET['state'] on fb callback

### ISSUE THREAD

**Issue by spedinfargo** [facebook/facebook-php-sdk-v4#583]
Hi,

This elusive error is still happening for numerous people (myself included):  **Facebook SDK returned an error: Cross-site request forgery validation failed. The "state" param from the URL and session do not match.**

As mentioned in #529, there is something very strange happening with the FBRLH_state session variable.  As soon as it gets back to my callback script, its value has been overwritten by a new random value.

I've tried to narrow it down a bit - maybe some more notes can help?

I have sites hosted on two providers:  one works with all browsers that I've tested, one is broken in these scenarios:

- Windows (broken):  Chrome, Firefox
- Windows (OK):  Internet Explorer, Edge
- Android (broken):  Chrome, Maxthon
- Android (OK):  Opera
- iOS (OK):  Safari, Chrome
- OS X (broken):  Safari

The site that works is running PHP 5.5.27 and I manually downloaded the Facebook SDK (which looks like it is still 5.0.0).  Unfortunately it looks like phpinfo() is disabled there and I'm betting I don't have access to the php.ini.

On the broken environment, I was originally using PHP 5.6 with the Facebook SDK installed using Composer, which I believe is the most current (5.1.2?).  However, I switched to PHP 5.5 using CPanel (confirmed the change) and also manually installed the 5.0.0 version (same as the site that works).  In other words, without changing any php.ini settings, I was hoping to create a similar environment.

On the site that doesn't work, I created a pretty standard Login page:

```
<?php
require_once __DIR__ . '/vendor/autoload.php';

session_start();

$fb = new Facebook\Facebook([
  'app_id' => '999999999', // Replace {app-id} with your app id
  'app_secret' => 'asdfasgasdfasdasdfa5',
  'default_graph_version' => 'v2.5',
  ]);

$helper = $fb->getRedirectLoginHelper();

$permissions = ['email']; // Optional permissions
$loginUrl = $helper->getLoginUrl('http://toriset.amutepoint.com/fbcallback.php', $permissions);

echo '<a href="' . htmlspecialchars($loginUrl) . '">Log in with Facebook!</a>';
?>

```
And then to make it even more incredibly simple, I don't do ANYTHING in the callback script except echo out the Session variables:

```
<?php
require_once __DIR__ . '/vendor/autoload.php';

session_start();

echo '<pre>';
var_dump($_SESSION);
echo '</pre>';
?>
```

Now, on the browsers that work, the FBRLH_state is the same as the state that is passed into via the URL.  However, on the browsers where it doesn't work, the session variable is completely different (still 32 characters).

I tried comparing payloads via Fiddler and I don't see anything unusual between calls from different browsers.

This just seems like some obscure setting in the PHP settings that is causing this Session variable difference.  It would be nice to narrow it down and document it.

As a workaround I'm doing this - I don't think it's as extreme as disabling the cross-site detection altogether:

In the login page, at the very end, create my own session variable:
`$_SESSION["FBRLH_persist"] = $_SESSION["FBRLH_state"];
`
And then at the very beginning of the callback page, override the bogus FBRLH_state to it's value:
`$_SESSION["FBRLH_state"] = $_SESSION["FBRLH_persist"];`

It's very confusing why my session variable persists and the FBRLH_state one does not.

btw, not sure if re-opening an issue or creating a new one is kosher here... flipped a coin and opened a new one.

**Comment by SammyK** [comment]
Hey @spedinfargo! Thanks so much for all the info!

Yes, this issue has plagued the PHP SDK v5 for a long time now. I've seen this issue pop up for so many around the internet and I've tried step debugging this line-by-line and still haven't found the source. The hardest part is just replicating the issue since it always work fine for me. Maybe we can put all our knowledge about it in this thread and narrow down the specific environment that's causing the CSRF token to get reset before or on the callback script. :)

Anyone out there have a specific environment that this issue is popping up on?

**Comment by spedinfargo** [comment]
I may have narrowed it down further.  I think @champsupertramp had the answer in #470:  it seems to have something to do with the session.save_path.  I'm wondering if this is a problem in shared hosting environments.

My provider has access to very rudimentary php settings override:  when I changed the default "/tmp" to "/home/mysitesname/tmp" things appear to have started working correctly.  I can see the session files created in that folder now and they seem to keep the FBRLH_state value correctly (along with my FBRLH_persist test variable).

This can also be done manually at the top of the script:

```
ini_set('session.save_path',realpath(dirname($_SERVER['DOCUMENT_ROOT']) . '/../tmp'));
session_start();

```
This assumes that you have a /tmp folder in your home directory.

Now, I have NO idea why this only affects certain browsers (as noted in my chart).  And I don't really know the ins-and-outs of how session variables actually work, especially when stored to a global /tmp folder (which I obviously don't have access to in a hosted environment).

Thoughts?

**Comment by yguedidi** [comment]
Thank you @spedinfargo for all those informations!

According you workaround, it seems it a problem that only affect shared hosting environment...

Just to check, if you print the `session_id()` at the end of the login page and ad the beginning of the callback, is it the same?

BTW, again according your workaround, a quick fix a can think of right now is to add the application id as part of the session key prefix.

**Comment by spedinfargo** [comment]
A few more notes.

I tried playing around with the FBRLH_ prefix a bit by changing the constant in FacebookSessionPersistentDataHandler.php.  I changed it to "ZFBRLH" and it didn't make a difference.  I also added a suffix so the session variable looked like FBRLH_state_ZZZ and that also didn't persist.

I also echoed the session_id() on both pages like you suggested - it shows the same for each page and it doesn't matter what browser.

I also tried copying the value of FBRLH_state to a temp variable and then back into FBRLH_state just to see if there was some sort of timing issue.  That didn't work either.  The strangest thing to me is that my FBRLH_persist session variable DOES persist just fine.  There is just something about whatever variable is being set by FacebookSessionPersistentDataHandler.php that gets clobbered.

Still the only thing that seems to work is changing my session.save_path to a folder under my /home directory...

**Comment by chynkm** [comment]
As per my understanding, in the Chrome browser the FBRLH_state variable is being generated twice.The initial FBRLH_state variable value is being passed to the Login url function.The FBRLH_state session variable contains the value generated in the second request.
Please find the log as following:-
```
[12-May-2016 09:07:42 UTC] --after intitalize--
[12-May-2016 09:07:42 UTC] --after getRedirectLoginHelper--
[12-May-2016 09:07:42 UTC] val: ad200c84d3de4109f7e5c03905bcac84
[12-May-2016 09:07:42 UTC] --after getLoginUrl--
[12-May-2016 09:07:46 UTC] --after intitalize--
[12-May-2016 09:07:46 UTC] --after getRedirectLoginHelper--
[12-May-2016 09:07:46 UTC] val: 4adf94796d5b2e332df3a2282bfaee41
[12-May-2016 09:07:46 UTC] --after getLoginUrl--
```
Please find the FB login url link as follows:-
https://example.com/v2.2/dialog/oauth?client_id=1045914366XXXXX&state=ad200c84d3de4109f7e5c03905bcac84&response_type=code&sdk=php-sdk-5.1.2&redirect_uri=http%3A%2F%2Fexample.com%2Fuser%2Ffb_login&scope=email%2Cpublish_actions

Hope this helps!

**Comment by spedinfargo** [comment]
@chynkm, Yes!  You're definitely on to something.

In the browsers that exhibit the bad behavior (Chrome), something is happening at the end of the logon PHP page where things get called again.

Here is my ugly code that shows exactly what's going on (apologize for my crappy way of logging messages).

```
<?php
error_log("-----\n", 3, "/home/mysite/tmp/my-errors.log");
error_log("11\n", 3, "/home/mysite/tmp/my-errors.log");

require_once __DIR__ . '/vendor/autoload.php';
error_log("22\n", 3, "/home/mysite/tmp/my-errors.log");

#ini_set('session.save_path',realpath(dirname($_SERVER['DOCUMENT_ROOT']) . '/../tmp'));
error_log("33\n", 3, "/home/mysite/tmp/my-errors.log");
session_start();
error_log("44\n", 3, "/home/mysite/tmp/my-errors.log");


$fb = new Facebook\Facebook([
  'app_id' => '999999999999999999', // Replace {app-id} with your app id
  'app_secret' => 'asdfasdfasdf',
  'default_graph_version' => 'v2.5',
  ]);
error_log("55\n", 3, "/home/mysite/tmp/my-errors.log");

$helper = $fb->getRedirectLoginHelper();
error_log("66\n", 3, "/home/mysite/tmp/my-errors.log");

$permissions = ['email']; // Optional permissions
error_log("77\n", 3, "/home/mysite/tmp/my-errors.log");
$loginUrl = $helper->getLoginUrl('http://example.com/fbcallback.php', $permissions);
error_log("88\n", 3, "/home/mysite/tmp/my-errors.log");

echo '<a href="' . htmlspecialchars($loginUrl) . '">Log in with Facebook!</a>';
error_log("99\n", 3, "/home/mysite/tmp/my-errors.log");

echo '<pre>';
var_dump($_SESSION);
echo '</pre>';
error_log("00\n", 3, "/home/mysite/tmp/my-errors.log");


echo "<br>";
echo session_id();
echo "<br>";
error_log("AA\n", 3, "/home/mysite/tmp/my-errors.log");

?>

```

If you can wade through the mess, you can see it's not doing very much (pretty much the standard sample code):  creating a Facebook object, creating a getRedirectLoginHelper object, calling the getLoginUrl method.  Everything else is just dumping the session info, etc.

I also put similar debug messages in the Facebook SDK itself.

So... when I run it in Chrome I get this:

```
-----
11
22
33
44
FacebookSessionPersistentDataHandler::construct
55
FacebookRedirectLoginHelper::constructor
66
77
FacebookRedirectLoginHelper::getLoginUrl
FacebookRedirectLoginHelper::makeUrl
FacebookSessionPersistentDataHandler::set
88
99
00
AA
FacebookSessionPersistentDataHandler::construct
FacebookRedirectLoginHelper::constructor
FacebookRedirectLoginHelper::getLoginUrl
FacebookRedirectLoginHelper::makeUrl
FacebookSessionPersistentDataHandler::set
```

Aaaaand on the browsers that work:

```
-----
11
22
33
44
FacebookSessionPersistentDataHandler::construct
55
FacebookRedirectLoginHelper::constructor
66
77
FacebookRedirectLoginHelper::getLoginUrl
FacebookRedirectLoginHelper::makeUrl
FacebookSessionPersistentDataHandler::set
88
99
00
AA

```

Wth?  As you can see, the debug line "AA" is definitely the absolute very last thing in my PHP file.  I don't have any stray <include> files or anything, shouldn't be anything out of the ordinary.  Why would the code decide to spin through the Facebook code a second time in this scenario?  Why only in some browser?

Even more interestingly, why would the second FBRLH_state get saved when the session location is shared and only the FIRST one gets saved when I set my session.save_path to a private directory?

Strange stuff...

**Comment by spedinfargo** [comment]
Possible Chromium bug?  

https://bugs.chromium.org/p/chromium/issues/detail?id=64810

**Comment by spedinfargo** [comment]
Definitely related to the Chromium "bug" (or feature if you want).  The problem is that some browsers request Favicon.ico in a bad way - it generates a second request to the web site and possibly runs your code twice.  If you don't have a Favicon.ico in the root of your web site, things get weird.  Tons of examples of strange effects in the comments of that bug.

My workaround:  create a dummy FavIcon.ico and place it in the root of my site.  Second call to the FacebookRedirectLoginhelper objects are gone.  Problem solved!

More good reading:  http://techblog.wimgodden.be/2011/02/22/how-a-bad-favicon-ico-can-cause-a-lot-of-trouble/

**Comment by spedinfargo** [comment]
OK, here is a better explanation of what's going on.  It's still a mystery to me why having a shared session.save_path makes a difference but it now makes sense why the missing favicon was causing the Facebook method from being called twice from my page.

Short answer:  it wasn't my page that was calling it twice.  It's an additional quirk of my server set up.

- Chrome made two calls to my server:  /fb.php and /favicon.ico.
- FaviIcon.ico was missing so the server generated a 404 error.
- My server is set up to redirect 404 requests to index.php
- My index.php ALSO had some Facebook code on it.  THIS is the actual PHP file that generated the second call to FacebookRedirectLoginhelper and generated and saved the second version of the FBRLH_state session variable.

So a couple of workarounds here:

- Add a FavIcon.ico to the root of your web site (probably good practice anyway)
- Reconfigure your site so that it doesn't redirect 404 errors to index.php
- Configure your php settings to use a private session.save_path (still not sure why this works)

@SammyK:  as you originally mentioned, definitely an environment issue (albeit a convoluted one) so I don't see any code change needed for the SDK.  Definitely something that could be addressed with doc or a blog post...

**Comment by GQwebsites** [comment]
OK, I managed to replicate Cross-site request forgery validation failed. The "state" param from the URL and session do not match over and over again. It happens when i load the Facebook.login page , click on the url it returns a token, Good, but if i leave that window open, then open another window load the Facebook.login page then click the link, it shows Cross-site request forgery validation failed. The "state" param from the URL and session do not match. 

I'm on a mac
homestead vagrant virtualbox
Laravel 5.2

**Comment by chrismerkle** [comment]
I could not figure out why Chrome kept failing on Android Samsung Galaxy S6.

Make sure the domain you login with matches EXACTLY to what is registered in Facebook and what redirect domain is. ie. if www.domain.com, redirect must include WWW. If domain.com is login then direction has to go to domain.com (no www).

**Comment by LeoGalleguillos** [comment]
I was able to resolve the issue using @spedinfargo's recommendations above. I could not figure out for the life of me why $_SESSION["FBRLH_state"] was being modified after being set by a single php script.

It turns out that Chrome, Firefox, and Safari all attempt to call favicon.ico, which results in a 404 page for my application. However, as I am using an MVC framework, the 404 page also calls the entire website layout, which has calls to Facebook's API within it. These Facebook calls also modify "FBRLH_state". So if a browser could not find favicon.ico, then "FBRLH_state" was essentially being set twice. This may explain why some developers have experienced issues with desktop browsers and not mobile (and vice versa).

My quick solution was to prevent $_SESSION["FBRLH_state"] from being modified on the 404 page.

**Comment by SammyK** [comment]
If anyone is still having issues with this, [upgrade to v5.2.1](https://github.com/facebook/facebook-php-sdk-v4/releases/tag/5.2.1) and it should fix most of these use-cases. :)

**Comment by Richard2012** [comment]
To anyone still struggling with the
**Cross-site request forgery validation failed. The "state" param from the URL and session do not match.**
issue.

The comment from [@chrismerkele](https://github.com/chrismerkle) solved my problem.
In the login script on the 
`$helper->getLoginUrl('https://mysite.com/fb_callback.php', $permissions)` 
line you should watch carefully to include, or not to include, the www. part in the url.
You must use the same domain notation as you have specified in the settings of your Facebook App under App Domains
