### ISSUE TITLE
[6.0][Proposal] Async Request

### ISSUE THREAD

**Issue by tolbon** [facebook/facebook-php-sdk-v4#588]
I see on roadmap of 6.0 support of Guzzle v6

It will be very interesting to support async Request with Promise on facebook sdk.

What's do you think about that ?

**Comment by SammyK** [comment]
Hey @tolbon! That's a great idea. Can you provide a few examples of how you propose adding an async API to the SDK? :)

**Comment by tolbon** [comment]
Ok it's really lite draft but,

I think it's not very helpful to have in HttpClientInterface
```
public function sendAsync($url, $method, $body, array $headers, $timeOut) 
{

}
```

```

```

**Comment by yguedidi** [comment]
@tolbon I suggest to use HTTPlug in the roadmap :)

**Comment by tolbon** [comment]
Yeah @yguedidi, I see your post

I take the example directly on HTTPlug : 

http://docs.php-http.org/en/latest/components/promise.html
http://docs.php-http.org/en/latest/clients/guzzle6-adapter.html

**Comment by SammyK** [comment]
Closing this since HTTPlug is on the roadmap in #605 :)
