### ISSUE TITLE
Can not make request with a different Facebook object using an access token

### ISSUE THREAD

**Issue by GVSO** [facebook/facebook-php-sdk-v4#596]
I'm working on a project in which people can log in using Facebook. My site is working fine with the login, but then some users might need to provide extra permissions after they sign in. So, I would like to check if they already have granted those permissions with something similar to:

```
$facebook = new \Facebook\Facebook(/* */);
$accessToken = $_SESSION['user_access_token'];
$facebook->setDefaultAccessToken($accessToken);
$id = $facebook->get('/me?fields=id')->getGraphNode()->getField('id');
```

_After I get the id, I can do some validations_

However, I'm getting an error stating: 
"Facebook\Exceptions\FacebookResponseException: Unknown path components: /me in Facebook\Exceptions\FacebookResponseException::create() (line 131 of vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php)."

I have printed my access token variable and it seems to be a valid one. Even when I then print the facebook object, it has the access token object as a property.

**Comment by SammyK** [comment]
What kind of access token are you using? Use the [access token debugger](https://developers.facebook.com/tools/debug/accesstoken/) to get more info on the access token.

**Comment by GVSO** [comment]
I got the following info on the access token:
```
App ID	1700833733535578 : Social API
User ID 899740766792000 : Valentin Sánchez Ozuna
        User last installed this app via API v2.x
Issued	1464009212 (on Monday)
Expires	1469193212 (in about 2 months)
Valid	True
Origin	Web
Scopes	email, public_profile
```

**Comment by SammyK** [comment]
Hey @GVSO! I think I misunderstood your original question. You can access what permissions the user has granted for your app by accessing the [`/me/permissions` endpoint](https://developers.facebook.com/docs/graph-api/reference/user/permissions).
