### ISSUE TITLE
Fatal error: Call to undefined function hash_equals() in Facebook/Helpers/FacebookRedirectLoginHelper.php on line 246

### ISSUE THREAD

**Issue by sarathjasrin** [facebook/facebook-php-sdk-v4#598]
I'm trying to get the basic info for the user. I'm following official docs. I don't know how to get rid of this error.

my code is below:

`session_start();
require_once 'Facebook/autoload.php';
$fb = new Facebook\Facebook([
  'app_id' => 'XXXXX', // Replace {app-id} with your app id
  'app_secret' => 'xxxxxxxxxx',
  'default_graph_version' => 'v2.2',
  ]);

$helper = $fb->getRedirectLoginHelper();

//Get the Access Token

try {
        //access token for the account
        $access_token=$helper->getAccessToken();

} catch (Facebook\Exceptions\FacebookResponseException $e) {
        echo 'Graph returned an erorr'. $e->getMessage();
        exit;
}catch(Facebook\Exceptions\FacebookSDKException $e){
        echo 'Graph returned an erorr'. $e->getMessage();
        exit;
}

var_dump($accessToken->getValue());

$loginUrl = $helper->getLoginUrl('https://startup-sarathjasrin.c9users.io/login/');

echo '<a href="' . htmlspecialchars($loginUrl) . '">Log in with Facebook!</a>';`

**Comment by SammyK** [comment]
Oops! This looks like a bug since we [added this](https://github.com/facebook/facebook-php-sdk-v4/blob/master/composer.json#L29) for those who use composer but we need to add an include to that in the autoloader.

This should be low hanging fruit - any takers? :)

**Comment by voku** [comment]
:) https://github.com/facebook/facebook-php-sdk-v4/pull/599/commits/40252bf7b74869e5d177b18e3546416d8d0ca6a7

**Comment by hardikuno1** [comment]
Hello.

I have used given solution but not fixed my bug. Please advise me.

I am getting same error like "Fatal error: Call to undefined function hash_equals() in D:\xampp\htdocs\facebookpostupdate\src\Facebook\Helpers\FacebookRedirectLoginHelper.php on line 246"

Here are my code file : 

Index.php 

session_start() ;
    require "./src/Facebook/autoload.php"; 
      
    $fb = new Facebook\Facebook([
        'app_id'     => '***************',
        'app_secret' => '***************',
        'default_graph_version' => 'v2.3',
    ]);
     
    $helper = $fb->getRedirectLoginHelper();
     
    $permissions = ['email', 'user_posts']; // optional
    $callback = 'http://localhost/facebookpostupdate/callback.php';
    $loginUrl = $helper->getLoginUrl($callback, $permissions);

    echo '<a href="'.$loginUrl.'">Log in with Facebook!</a>';



Callback.php

<?php 
    session_start() ;
    require "./src/Facebook/autoload.php"; 
    
    $fb = new Facebook\Facebook([
        'app_id'     => '***********',
        'app_secret' => '***********',
        'default_graph_version' => 'v2.2',
    ]);

    $helper = $fb->getRedirectLoginHelper();
    
    try {
      $accessToken = $helper->getAccessToken();
    } catch(Facebook\Exceptions\FacebookResponseException $e) {
      // When Graph returns an error
      echo 'Graph returned an error: ' . $e->getMessage();
      exit;
    } catch(Facebook\Exceptions\FacebookSDKException $e) {
      // When validation fails or other local issues
      echo 'Facebook SDK returned an error: ' . $e->getMessage();
      exit;
    }
    echo $accessToken;
    if (isset($accessToken)) {
      // Logged in!
      $_SESSION['facebook_access_token'] = (string) $accessToken;

      // OAuth 2.0 client handler
    $oAuth2Client = $fb->getOAuth2Client();

    // Exchanges a short-lived access token for a long-lived one
    $longLivedAccessToken = $oAuth2Client->getLongLivedAccessToken($_SESSION['facebook_access_token']);


    // Sets the default fallback access token so we don't have to pass it to each request
    $fb->setDefaultAccessToken($longLivedAccessToken);

    try {
      $response = $fb->get('/me?fields=email');
      $userNode = $response->getGraphUser();
    } catch(Facebook\Exceptions\FacebookResponseException $e) {
      // When Graph returns an error
      echo 'Graph returned an error: ' . $e->getMessage();
      exit;
    } catch(Facebook\Exceptions\FacebookSDKException $e) {
      // When validation fails or other local issues
      echo 'Facebook SDK returned an error: ' . $e->getMessage();
      exit;
    }

    echo 'Logged in as ' . $userNode->getName();

    $graphObject = $response->getGraphObject();
    $email = $graphObject->getProperty('email');  // This is not getting any thing

    echo $email; // Empty

    }
?>

**Comment by SammyK** [comment]
This will be fixed in #599. :)
