### ISSUE TITLE
Posting on /me/video accepts the 'thumb' parameter, however it does not post the thumb as the video's thumbnail.

### ISSUE THREAD

**Issue by steve-tapgen** [facebook/facebook-php-sdk-v4#600]
Posting on /me/video accepts the 'thumb' parameter, however it does not post the thumb as the video's thumbnail.

Example code:
$thumb = 'https://website.com/example.png';
$title = 'Check out my video';
$videoFileURL = 'https://website.com/example.mp4';
$description = 'Check out my video';

$thumbFile = $this->fb->fileToUpload($thumb);

$data = [
  'title' => $title,
  'thumb' => $thumbFile,
  'file_url' => $videoFileURL,
  'description' => $description
 ];

$response = $fb->post('/me/videos', $data, $accessToken);

it posts the video, but seems like the thumbnail isn't used.  I haven't included actual URLs, you can substitute your own, but thumb doesn't get posted.

**Comment by SammyK** [comment]
This seems to be a bug with the Graph API and not the PHP SDK.

<img width="962" alt="screen shot 2016-04-11 at 1 12 38 pm" src="https://cloud.githubusercontent.com/assets/578780/15683350/74896e12-2727-11e6-8ced-57f8fe024a42.png">

<img width="862" alt="screen shot 2016-05-31 at 11 52 47 am" src="https://cloud.githubusercontent.com/assets/578780/15683349/7488c444-2727-11e6-8246-f85587656004.png">

I've [submitted a bug report](https://developers.facebook.com/bugs/1042527215784313/) to the Graph API people. :)

**Comment by SammyK** [comment]
Update: this bug has been [confirmed](https://developers.facebook.com/bugs/1042527215784313/) with the Graph API nerds and they are assigning it to someone to get it fixed. :)
