### ISSUE TITLE
Uncaught Error: Call to undefined methodFacebookRequest::execute() in

### ISSUE THREAD

**Issue by sparx1234** [facebook/facebook-php-sdk-v4#603]
I'm trying to get the app access token info (like-expiry date) using graph API but when i'm making graph api call it giving me a fatel error, here is my code : 

$accessToken = 'My_Access_Token';
            $request = new Facebook\FacebookRequest($session, 'GET', '/debug_token?input_token={' . $accessToken . '}');

            $response = $request->execute();
            $graphObject = $response->getGraphObject();

            echo '<pre>';
            print_r($graphObject);
            echo '</pre>';

Error Message is :  Fatal error: Uncaught Error: Call to undefined method Facebook\FacebookRequest::execute() in

**Comment by yguedidi** [comment]
Looks like your code use SDK v4 but you installed v5 :)

**Comment by sparx1234** [comment]
Well i took reference from here https://developers.facebook.com/docs/graph-api/reference/v2.6/debug_token .

So how do we make request in v5?

**Comment by SammyK** [comment]
@sparx1234 Yeah, that's what issue #509 is about. Hopefully it'll get fixed soon enough. :)

In v5, you make requests like this:

```php
$fb = new \Facebook\Facebook([
  'app_id' => 'your-app-id',
  'app_secret' => 'your-app-secret',
  'default_graph_version' => 'v2.6',
  ]);

try {
  $response = $fb->get('/debug_token?input_token='.$tokenToDebug, 'your-app-access-token');
} catch(\Facebook\Exceptions\FacebookSDKException $e) {
  echo 'Error: ' . $e->getMessage();
  exit;
}

var_dump($response->getDecodedBody()); // Returns an array
```

Or you can make use of the built-in access token debugging methods:

```php
$fb = new \Facebook\Facebook([/* */]);
$client = $fb->getOAuth2Client();

try {
  $tokenInfo = $client->debugToken($tokenToDebug); // Returns a AccessTokenMetadata entity
} catch(\Facebook\Exceptions\FacebookSDKException $e) {
  echo 'Error: ' . $e->getMessage();
  exit;
}

var_dump($tokenInfo->getField('expires_at'));
// ...or
var_dump($tokenInfo->getExpiresAt());
```

**Comment by ShivamSharmaRep** [comment]
I'm having the same error while i'm trying to get ratings of a page via using php graph API i'm making graph api call it giving me a fatel error, Below is the code i'm using:

require_once __DIR__ . '/facebook-sdk-v5/autoload.php';

use Facebook\FacebookRequest;

$request = new Facebook\FacebookRequest(
  $session,
  'GET',
  '/{page-id}/ratings'
);
$response = $request->execute();
$graphObject = $response->getGraphObject();

var_dump($graphNode); 


Fatal error: Uncaught Error: Call to undefined method Facebook\FacebookRequest::execute() in C:\xampp\htdocs\fb_reviews\sdk\index.php:11 Stack trace: #0 {main} thrown in C:\xampp\htdocs\fb_reviews\sdk\index.php on line 11 

its first time i'm using any api and got stuck here, any help..

**Comment by SammyK** [comment]
Hey @ShivamSharmaRep - you're using v4 syntax. See the [v5 docs for making GET requests](https://github.com/facebook/php-graph-sdk/blob/5.4/docs/examples/retrieve_user_profile.md).
