### ISSUE TITLE
Error with login for our users: Bad Request.

### ISSUE THREAD

**Issue by anaychowdhary** [facebook/facebook-php-sdk-v4#611]
We are trying to upgrade to v5. I'm following the original docs. For a new user(first time) login, we keep getting Bad Request error.

Here's our code - 

**For Login Page** --

session_start();
require_once 'vendor/autoload.php';
$FB = new Facebook\Facebook([
  'app_id'     => $appId,
  'app_secret' => $appSecret,
  'default_graph_version' => 'v2.5',
  ]);
$helper = $FB->getRedirectLoginHelper();
$login_url = "login.php";
$FBloginUrl = $helper->getLoginUrl($login_url, $facebook_app_permissions)."&auth_type=rerequest";

**For CallBack Page** --

session_start();
require_once 'vendor/autoload.php';
$FB = new Facebook\Facebook([
  'app_id'     => $appId,
  'app_secret' => $appSecret,
  'default_graph_version' => 'v2.5',
  ]);
try {
  $accessToken = $helper->getAccessToken();
}catch(Facebook\Exceptions\FacebookResponseException $e) {
  log_error( $e , "fblogin facebook response exception - graph api" );
} catch(Facebook\Exceptions\FacebookSDKException $e) {
  log_error( $e , "fblogin facebook sdk exception - validation or local issues" );
}

if (! isset($accessToken)) {
  if ($helper->getError()) {
    log_message( "Error: Login => Code - ".$helper->getErrorCode()." , ".$helper->getErrorReason()." , ".$helper->getErrorDescription(), "fblogin helper error" );
  } else {
    _**log_message( "Error: Login => Bad Request ", "fblogin helper error" );**_
  }
  exit;
}

$fb_access_token = (string) $accessToken;

$FB->setDefaultAccessToken($fb_access_token);

--End of Code--

For first time login for every user, we get the Bad Request error. Basically helper does not return any error and neither is access token set. It does not happen if the user tries to login a second time right after or sometime later.
Can you help us understand why this may be happening?

Thanks.

**Comment by SammyK** [comment]
The `$login_url` needs to be the full URL to the callback page.

Also, this line:

```php
$FBloginUrl = $helper->getLoginUrl($login_url, $facebook_app_permissions)."&auth_type=rerequest";
```

Looks like you're trying to turn the login link into a rerequest link. If it's the user's first time logging in, they just need a normal login link. So you can remove the `."&auth_type=rerequest"` part. If you want to explicitly generate a rerequest link, you'll need to use the method dedicated to that. Here's an example of both types of links:

```php
// Login Link
$FBloginUrl = $helper->getLoginUrl($login_url, $facebook_app_permissions);

// Rerequest Link
$FBloginUrl = $helper->getReRequestUrl($login_url, $facebook_app_permissions);
```

Hope that helps! :)
