### ISSUE TITLE
Specific calls to facebook GET will result to incorrect FacebookResponse

### ISSUE THREAD

**Issue by ericonuki** [facebook/facebook-php-sdk-v4#614]
If you make a call to the method get('me/picture?type=large), the object returned from facebook will have an empty body and the response will be somewhere inside the header.
![screen shot 2016-06-18 at 14 32 54](https://cloud.githubusercontent.com/assets/5102794/16172970/95f1e802-3561-11e6-813b-1946f1f3fc22.png)

**Comment by SammyK** [comment]
Make sure to add `redirect=false` to the query params:

`me/picture?type=large&redirect=false`

See [the docs](https://developers.facebook.com/docs/graph-api/reference/user/picture/) for more info.
