### ISSUE TITLE
Document some basic, but important changes to fetching fields when upgrading

### ISSUE THREAD

**Issue by holtkamp** [facebook/facebook-php-sdk-v4#615]
When upgrading from v4 to v5 using @SammyK's [great guide](https://www.sammyk.me/upgrading-the-facebook-php-sdk-from-v4-to-v5) to use the Facebook API 2.6, it took me some time to realize that:

- one has to explicitly indicate which fields to fetch from the Graph API (in former versions of the API, some fields were always returned):

```php
$fields = [
    'id',
    'email',
    'name',
    'first_name',
    'middle_name',
    'last_name',
];
$response = $facebook->get(sprintf('/me?fields=%s', implode(',', $fields)), $facebookAccessToken);
$result = $response->getGraphUser();
```
- one has to explicitly indicate the permissions required to fetch these fields when generating the loginUrl
 - a mistake I made was to request permission to access ```first_name```, ```middle_name```, ```last_name```, instead of ```public_profile```, also documented [here](https://developers.facebook.com/docs/facebook-login/permissions#reference-public_profile)

Maybe these mistakes can be classified as rookie mistakes, but I do not spend that much time tracking the changes in the Facebook API 😄 and I guess it can help others.

Maybe this can be included to the upgrade guide... This might also justify adding a ```$fields``` parameter to the ```get()``` function in ```6.0.0```?

**Comment by karolszklarski** [comment]
Same here about fetching fields. I've just spent some time debugging why some fields are missing, to discover that I have to explicitly name them in ?fields=something

**Comment by zoonman** [comment]
The Graph API supports introspection of nodes. This enables you to see all of the edges a node has without knowing its type ahead of time. To get this information, add metadata=1 to the Graph API request ```GET graph.facebook.com/{node-id}?    metadata=1```

**Comment by SammyK** [comment]
Thanks for the feedback @holtkamp! :) I'll add this on my TODO list to update the blog post.
