### ISSUE TITLE
How we can logout user using api please provide code

### ISSUE THREAD

**Issue by tushar4monto** [facebook/facebook-php-sdk-v4#616]
Hello
I have used this SDK for my site. I have successfully logged in user using this api but. I want to logout user with logout button of my website page . will also logout user to Facebook .
Also how i can get other details after user login from facebook like user email id login name etc ?

**Comment by SammyK** [comment]
Hey @tushar4monto! The logout `FacebookRedirectLoginHelper::getLogoutUrl()` will log a user out of Facebook which is usually not the desired user experience. If you want to logout a user who signed in with Facebook, just clear your session on your sever. https://developers.facebook.com/docs/php/FacebookRedirectLoginHelper/5.0.0
