### ISSUE TITLE
Not redirect to particular page

### ISSUE THREAD

**Issue by santoshroy18** [facebook/facebook-php-sdk-v4#617]
http://hindi.nametests.in/test/38/your-name-meaning-hind?code=AQAGdbn6QgCSxRqLLZI9d-g21HJd9YbpwHH4IiaARGIIE0wopvq_8xXUXNpFCTURVLF0T8IhurtyVYdGUPWh9olLgkI_f6w-eskmVW_BlqXs8zGIoPUkT_8T4xNthudmybEyU--pkteRR7YWklyYIoeT_psDptrsCBjehVhA__1AFL8OMfy7ImKqTIArIHKN0t-gI3VivEI3GbOfy87CtubrHLtYGo5JtfRcA3dBxJIW_XRA_3SxTGEXtX2f86T9bZ2STipfDuAFgwM114vBMopfpK3uHXblL_Nsguso6I7aiGM9faH3jVHkn2rs4GuYMYbhtWIse0e6ngnO-CJxCF7R&state=19f5aab94c0c416c5e3a47aa93c3cf04#_=_

Here my website.. Sometimes its just showing this long code and remain on same page instead of redirecting into next page.. Please help me to solve this problem..

**Comment by SammyK** [comment]
Hey @santoshroy18! Can you provide any relevant code to further debug this issue? :)

**Comment by SammyK** [comment]
I'm closing this one, but if you're still having trouble, feel free to chime in! :)
