### ISSUE TITLE
"The parameter app_id is required" error

### ISSUE THREAD

**Issue by wzup** [facebook/facebook-php-sdk-v4#620]
What does this error mean?

![- google chrome 2016-07-20 14 14 23](https://cloud.githubusercontent.com/assets/3880497/16976820/54e303a0-4e84-11e6-9238-7f6fca3eb971.png)

Put this url in browser search bar and hit enter (from here https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#login):
```
https://www.facebook.com/dialog/oauth?
  client_id={app-id}
  &redirect_uri={redirect-uri}
```
You'll get that error. Why? What kind if `app_id` is needed? Your docs say:

> client_id. The ID of your app, found in your app's dashboard.

So `client_id` is exactly `app_id`. Why do I get the error then? Why the error is so uninformative?

**Comment by SammyK** [comment]
Hey @wzup! You need to create an app at https://developers.facebook.com/apps and enter the app's ID for the `client_id` param. Hope that helps! :)

**Comment by dykyi-roman** [comment]
its not help
