### ISSUE TITLE
SDK version 5.2 cannot Auth and get an access-token

### ISSUE THREAD

**Issue by typoworx-de** [facebook/facebook-php-sdk-v4#622]
I've tried composer install of SDK version 5.2 with example code provided. I cannot get an access-token using getRedirectLoginHelper and getLoginUrl methods.

The Link generated fails with the following error:
```
The parameter redirect_uri is required
```

After a long time of fiddling around, it turned out that the helper-method does NOT attach the redirect-url that I provide to that method. Attaching it manually with &next=[callback-url] does work.

**Comment by SammyK** [comment]
Hey @typoworx-de! The `getLoginUrl()` method requires the callback URL in the first argument:

```php
$fb = new Facebook\Facebook([/* . . . */]);
$helper = $fb->getRedirectLoginHelper();

$permissions = ['email', 'user_posts']; // optional
$callback = 'http://example.com/fb-login-callback.php';
$loginUrl = $helper->getLoginUrl($callback, $permissions);

echo '<a href="'.$loginUrl.'">Log in with Facebook!</a>';
```

Is this how you are using it?
