### ISSUE TITLE
Bad MethodCallExeption

### ISSUE THREAD

**Issue by mamulasa** [facebook/facebook-php-sdk-v4#624]
Hi, 
I have used the basic example from here https://github.com/SammyK/LaravelFacebookSdk#user-login-from-redirect-example

and receive this message "BadMethodCallException in Builder.php line 2345:
Call to undefined method Illuminate\Database\Query\Builder::createOrUpdateGraphNode()" I have no idea how to solve this?!

**Comment by SammyK** [comment]
Hey @mamulasa. This is the repo for the official Facebook PHP SDK. :) If you have an issue with the SammyK/LaravelFacebookSdk repo you can submit an issue there: https://github.com/SammyK/LaravelFacebookSdk/issues
