### ISSUE TITLE
Facebook JavaScript Login Helper return session as null

### ISSUE THREAD

**Issue by saikiranmarripati** [facebook/facebook-php-sdk-v4#625]
I am getting session as null from FacebookJavascriptHelper

$.ajaxSetup({ cache: true });
$.getScript('//connect.facebook.net/en_US/sdk.js', function(){
    
    FB.init({
      appId: '{app_id}',
      version: 'v2.6',
      channelUrl : '', 
      status     : false, 
      cookie     : true, 
      oauth      : true, 
      xfbml      : true  
    });  

    FB.getLoginStatus(function(response) {

      FBLoginStatus=response.status;

    },true);
});

**PHP:**

      FacebookSession::setDefaultApplication( 'api_id' ,'app_secret' );
      $this->helper = new FacebookJavaScriptLoginHelper();

        try {

          $this->session = $this->helper->getSession(); 

        } catch( FacebookRequestException $ex ) {
            echo 'Facebook exception code :' . $ex->getCode()."<br>";
            echo 'FacebookRequestException: ' . $ex->getMessage();
            die();
        } catch( Exception $ex ) {
           // When validation fails or other local issues
           echo 'Graph returned an error: ' . $ex->getMessage();
           die();
        }

This is was working fine till yesterday and started throwing me error

Facebook exception code :100
FacebookRequestException: This authorization code has expired.

Help me!!

**Comment by SammyK** [comment]
Hey @saikiranmarripati! The access token has expired. Consider exchanging a short-lived access token with a long-lived access token. See a full example here: https://developers.facebook.com/docs/php/howto/example_facebook_login
