### ISSUE TITLE
Catchable Fatal Error: Argument 3 passed to

### ISSUE THREAD

**Issue by DenoBY** [facebook/facebook-php-sdk-v4#627]
`Catchable Fatal Error: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given, called in /var/www/smmonsters.net/vendor/guzzlehttp/guzzle/src/Client.php on line 87 and defined` 

What error may be related? I make to the framework, symfony.

**Comment by SammyK** [comment]
Hey @DenoBY! Can you provide any relevant code that would help debug this issue? :)

**Comment by DenoBY** [comment]
@SammyK I was Guzzle library, and it was imposed on FB SDK API (I apologize for my bad english)

**Comment by SammyK** [comment]
Hey @DenoBY! Specifically, can you copy & paste the snippet of code that's causing this error? :)

**Comment by jonasmenk** [comment]
I just ran into the same error. It happens if you use Guzzle 6.x instead of 5.x.
As Guzzle is only a dev-dependency for facebook-php-sdk-v4, it can be installed like this withouth errors.

**Comment by SammyK** [comment]
Thanks @j0nsch!

@DenoBY Check out this guide to [get the Facebook PHP SDK working with Guzzle v6](https://www.sammyk.me/how-to-inject-your-own-http-client-in-the-facebook-php-sdk-v5#writing-a-guzzle-6-http-client-implementation-from-scratch).

**Comment by cyberhck** [comment]
easy workaround is to install PHP's curl extension.
