### ISSUE TITLE
Fatal error: Uncaught exception '(#32) Page request limited reached'

### ISSUE THREAD

**Issue by ma4xat** [facebook/facebook-php-sdk-v4#634]
I left the image with the error here:

![image](https://cloud.githubusercontent.com/assets/3372517/17514933/be916484-5e35-11e6-96b4-f0d43f7f3ea4.png)

And the code:

`Fatal error: Uncaught exception 'Facebook\Exceptions\FacebookAuthenticationException' with message '(#32) Page request limited reached' in /home/www/app/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php:131 Stack trace: #0 /home/www/app/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse)) #1 /home/www/app/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException() #2 /home/www/app/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody() #3 /home/www/app in /home/www/app/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php on line 131`

**Comment by ma4xat** [comment]
Facebook Page Rate Limitation was implemented on July 11 this year.

**Comment by SammyK** [comment]
Hey @ma4xat! Looks like the requests your app is making are being throttled. You can check the response headers for the rate limit info:

```
X-Page-Usage : {'call_count' : 85, 'total_cputime' : 56, 'total_time' : 60}
```

And you can also see the rate limits in your app dashboard.

**Comment by ma4xat** [comment]
Hi @SammyK !

First, sorry, cause english is not my first language and i dont explain so well :( .

I know why i get that error, but i create this issue cause i thought that error logs was more "beautiful" and that error type wasnt implemented.

I try others errors and i see that its always with the same format ( Falta error: XXXX and so on ) so, is not a "not implemented error" anymore and just keep this issue closed :D, but errors could be more "beautiful", like this:

![image](https://cloud.githubusercontent.com/assets/3372517/17515857/394808cc-5e3b-11e6-8731-3655cdace0dc.png)

Happy coding! :D

**Comment by SammyK** [comment]
Hey @ma4xat! Thanks for the feedback! We typically leave the error handling to the application or framework that is implementing the SDK so that we don't add too much extra code to the SDK. I hope that answers your question! :)

**Comment by ma4xat** [comment]
Yeah @SammyK , that's answer me =)

Thanks for ur time and ur speed answer the issues =)
