### ISSUE TITLE
Batch Request processes but throws an uncaught exception.

### ISSUE THREAD

**Issue by geconly** [facebook/facebook-php-sdk-v4#635]
I have thrown this error:

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Argument for add() must be of type array or FacebookRequest.' in /home/my_host/public_html/development/application/vendor/facebook/php-sdk-v4/src/Facebook/FacebookBatchRequest.php:85 Stack trace: #0 /home/my_host/public_html/development/application/vendor/facebook/php-sdk-v4/src/Facebook/FacebookBatchRequest.php(78): Facebook\FacebookBatchRequest->add(Object(Facebook\FacebookResponse), 0) #1 /home/my_host/public_html/development/application/vendor/facebook/php-sdk-v4/src/Facebook/FacebookBatchRequest.php(61): Facebook\FacebookBatchRequest->add(Array) #2 /home/my_host/public_html/development/application/vendor/facebook/php-sdk-v4/src/Facebook/Facebook.php(492): Facebook\FacebookBatchRequest->__construct(Object(Facebook\FacebookApp), Array, 'EAAYzEGW0ZAsoBA...', 'v2.7') #3 /home/my_host/public_html/development/application/controllers/user/event.php(777): Facebook\Facebook->sendBatchRequest(Array, 'EAAYzEGW0ZAsoBA...') #4 [internal function]: Event->add in /home/my_host/public_html/development/application/vendor/facebook/php-sdk-v4/src/Facebook/FacebookBatchRequest.php on line 85

I am creating the batch as such (in Codeigniter):

```
try {			

  $responses = $fb->sendBatchRequest(($batch), $this->session->userdata('fb_access_token'));
```

Where $batch is defined by a series of events with different starting dates:

```
foreach($esdarr as $key => $event_start_datetime){
		$sched_time = strtotime($event_start_datetime)- 18000;
		$event_end_datetime = $eedarr[$key];
		$batch[$key] = $fb->post('/'.$band_page_id.'/feed', ['message' => $band_name.' is playing today at '.$venue_name.' '.date('(l), g:ia', strtotime($event_start_datetime)), 'published'=>false, 'scheduled_publish_time'=>$sched_time], $pageToken);
		
			}
```

When I add scheduled posts, they are successfully added to my software, **and** are added to my FB test account successfully! The exception is thrown (which breaks the process). **However**, when I add a redirect before line 85 of FacebookBatchRequest.php:

```
public function add($request, $name = null)
    {
        if (is_array($request)) {
            foreach ($request as $key => $req) {
				 
                $this->add($req, $key);
            }
 
            return $this;
        }

        if (!$request instanceof FacebookRequest) {
```		
Line 85 *FacebookBatchRequest.php*
```
	redirect('user/event');

            throw new \InvalidArgumentException('Argument for add() must be of type array or FacebookRequest.');
        }

        $this->addFallbackDefaults($request);
        $requestToAdd = [
            'name' => $name,
            'request' => $request,
        ];

        // File uploads
        $attachedFiles = $this->extractFileAttachments($request);
        if ($attachedFiles) {
            $requestToAdd['attached_files'] = $attachedFiles;
        }
        $this->requests[] = $requestToAdd;

        return $this;
    }
```

Everything works fine (i.e. no exceptions and the posts are properly scheduled. If I just comment out the thrown error, the process again breaks (because $request is not an instance of FacebookRequest. I don't quite understand how the add() iterates, but **Could this be a bug?**

**Comment by SammyK** [comment]
Hey @geconly! It looks like the problem is with this line:

```php
$batch[$key] = $fb->post('/'.$band_page_id.'/feed', ['message' => $band_name.' is playing today at '.$venue_name.' '.date('(l), g:ia', strtotime($event_start_datetime)), 'published'=>false, 'scheduled_publish_time'=>$sched_time], $pageToken);
```

The `post()` method creates a request and also sends it to the Graph API. To generate requests for use in `sendBatchRequest()` you'll need to use the [`request()` method](https://developers.facebook.com/docs/php/FacebookBatchRequest/5.0.0) so the the requests get generated but not sent to the Graph API right away:

```php
$batch[$key] = $fb->request('POST', '/'.$band_page_id.'/feed', ['message' => $band_name.' is playing today at '.$venue_name.' '.date('(l), g:ia', strtotime($event_start_datetime)), 'published'=>false, 'scheduled_publish_time'=>$sched_time], $pageToken);
```

See also:
- https://developers.facebook.com/docs/php/Facebook/5.0.0#request
- https://developers.facebook.com/docs/php/Facebook/5.0.0#send-batch-request

Hope that helps! :)
